-- apply-0014.sql: applies neon/migrations/0014_publish_reply.sql (P4.6 Google
-- Business Profile review-reply publishing: four deliveries columns target_ref,
-- provider_receipt, failure_reason and verified_at, output_versions.first_published_at,
-- the guarded deliveries_publish_target_check, the two partial unique indexes
-- deliveries_active_publish_version_key and deliveries_active_publish_target_key,
-- the three SECURITY INVOKER functions begin_publish_output_version,
-- finish_publish_output_version and cancel_published_reply, and
-- export_output_version re-created with the DEC-14 change, EXECUTE granted to
-- sme_app_runtime only) to a database whose migration journal holds exactly
-- 0001-0013, and records journal row 14, in one transaction.
--
-- What it does, in order, inside one DO block (one statement, one transaction):
--   1. SET LOCAL ROLE smeassistant_migrator, then refuses unless current_user is
--      that role, so every object 0014 creates or replaces is owned by the migrator.
--   2. Takes the migration runner's advisory lock, pg_advisory_xact_lock(1936549221, 3)
--      (scripts/neon/migrations.ts).
--   3. Refuses unless neon_migrations.journal is exactly ordinals 1-13, with the
--      names and sha256 checksums of neon/migrations/0001-0013 as loadMigrations()
--      computes them.
--   4. Executes the exact text of 0014_publish_reply.sql.
--   5. Checks the result (spec section 1.6): the five new columns, the CHECK
--      constraint, both partial unique indexes, the four functions owned by the
--      migrator as SECURITY INVOKER with search_path '' and EXECUTE for
--      sme_app_runtime but not PUBLIC, and the md5 of export_output_version's
--      body ('33952a4e8f01eb27e5078bfad12163bc').
--   6. Inserts journal row (14, '0014_publish_reply.sql', 'e2c181b78e1e2015cf624e4465b0b392b02db2ac74c157f4cb5679e0233097a3').
-- Any refusal, failed check or error rolls the whole statement back; nothing is
-- changed.
--
-- How to run: in the Neon SQL Editor, logged in as neondb_owner, paste and run
-- this whole file. neondb_owner must hold smeassistant_migrator WITH SET TRUE;
-- without it the statement fails with "permission denied to set role".
-- On success Postgres reports one notice:
-- "apply-0014: applied 0014_publish_reply.sql and recorded journal row 14".
--
-- Run it on a Neon test branch of production first, then on production.
-- Applying it is NOT required before deploying the P4.6 code: while
-- GBP_REPLY_PUBLISH_ENABLED is unset the publish card, the targets and publish
-- routes and the delete route check the flag first and issue no SQL, and the
-- reconcile route and the page loader read no 0014 column unless a publish
-- delivery exists, which cannot exist before 0014
-- (test/integration/neon-publish-flag-off.integration.test.ts proves it against
-- a database that stops at 0013). It IS required before setting
-- GBP_REPLY_PUBLISH_ENABLED=true: with the flag on and no 0014 a publish fails
-- at begin_publish_output_version and answers "unavailable".
-- Applying it does change one existing function: export_output_version is
-- re-created so that a version counts at most once, at its first export or its
-- first verified publish (DEC-14). Until a publish has finished,
-- output_versions.first_published_at is null on every row, so the new body
-- counts exports exactly as the 0011 body did; applying it ahead of the deploy
-- changes nothing for owners. Everything else is additive.
-- 0013 (apply-0013.sql) must already be applied: this statement refuses any
-- other journal. A second run refuses with the journal message and changes
-- nothing.
--
-- Do not edit this file. It was generated from the migration files on disk
-- (neon/migrations/0001-0014); the embedded 0014 text and the checksums must
-- match them byte for byte, or the repository runner will later refuse the
-- journal with migration_checksum_mismatch. It contains no secrets.
DO $apply$
DECLARE
  expected CONSTANT text[] := ARRAY[
    '1 0001_identity.sql f2e65e08e94c6514735db9a7eb6b0dcc5ec522732e2fb3e573b02b62aedb60fa',
    '2 0002_business.sql 34c46b53bc08e12d7c76d365c177877890ebadec27fbf4d7836e253d901021a1',
    '3 0003_workflows.sql b8f80980ab7758ae068bcab9dfea4ae0fcc6cc78b2ed49b6410c92b103a12ab1',
    '4 0004_atomic_operations.sql b24f2cbba79881d1f97118e05a5d7990a847fdaed6ecd5461682f404af076069',
    '5 0005_owner_removal_guard.sql c4349d2ba9a24a595b37ed547574e8231ee5ff0eb717ef8ffa5fad1fa093c26b',
    '6 0006_action_applications.sql ea0f7471c0b469a5e99b884557224b542b920a0aadc7f1f49223697334a4be47',
    '7 0007_action_verification.sql e9f8132aa98021c7f2861b9e3fdc2e0f3847445b91ee955683ce696770f43d11',
    '8 0008_workspace_internal.sql f9f03d6c1d70231871e2e683c9318c98f55afbd0fd125a43e712d328f019d678',
    '9 0009_scan_attempts.sql 3c35ab9965be1d4821e885a2e43676c743e62f25435e4d59bd46d2c34a3d1768',
    '10 0010_mail_outbox.sql ec50dceefbc20b2acbf14cf8908a550bc5c65e9feda346fd57338f1e0edce69c',
    '11 0011_offers.sql 5d5a01b5796f579884de31b31aece3d54159f0b42a06042f7b228b93b0eb9449',
    '12 0012_work_packs.sql e7933f6caac57dbc7384aae24c0fd86316cf3b521167432fe483df58cc9b7289',
    '13 0013_preview_events.sql 98ec68e18a5281885ac12497af8328c3c7300ce7adfd1869f74f62912160cf24'
  ];
  found text[];
  missing text;
  fn text;
  p record;
BEGIN
  SET LOCAL ROLE smeassistant_migrator;
  IF current_user::text <> 'smeassistant_migrator' THEN
    RAISE EXCEPTION 'apply-0014 refused: running as %, not smeassistant_migrator', current_user;
  END IF;

  PERFORM pg_advisory_xact_lock(1936549221, 3);

  SELECT coalesce(array_agg(ordinal::text || ' ' || name || ' ' || checksum ORDER BY ordinal), ARRAY[]::text[])
    INTO found
    FROM neon_migrations.journal;
  IF found IS DISTINCT FROM expected THEN
    RAISE EXCEPTION 'apply-0014 refused: neon_migrations.journal is not exactly 0001-0013 with the expected checksums (it has % rows)', cardinality(found);
  END IF;

  EXECUTE $m0014$-- P4.6 Google Business Profile review-reply publishing (docs/superpowers/specs/2026-10-04-gbp-reply-publish-design.md §1).
--
-- A publish is a delivery with mode 'publish' and channel 'google_business'.
-- It starts 'publishing' (begin), then becomes 'published' or 'failed'
-- (finish); an owner may later mark a published reply 'cancelled' (cancel).
-- target_ref names the review (accounts/{a}/locations/{l}/reviews/{r}).
-- provider_receipt holds only non-secret identifiers ({ review_name,
-- reply_update_time }) and failure_reason only a reason code. Review text,
-- reviewer names and reply text are never stored on a delivery; the reply text
-- is output_versions.body.
--
-- DEC-14: a version counts at most once, at its first export or its first
-- verified publish, whichever comes first. output_versions.first_published_at
-- records the first verified publish; "never counted" is
-- first_exported_at IS NULL AND first_published_at IS NULL. Only SQL counts.
--
-- At most one active publish (publishing or published) per version and per
-- target: the functions check it under the version lock, and the two partial
-- unique indexes are the backstop for races.
--
-- No table or foreign key is added, so the delete graph is unchanged. All
-- functions are SECURITY INVOKER, like 0004, 0011 and 0013 (neon/README.md).
ALTER TABLE public.deliveries ADD COLUMN IF NOT EXISTS target_ref text;
ALTER TABLE public.deliveries ADD COLUMN IF NOT EXISTS provider_receipt jsonb;
ALTER TABLE public.deliveries ADD COLUMN IF NOT EXISTS failure_reason text;
ALTER TABLE public.deliveries ADD COLUMN IF NOT EXISTS verified_at timestamptz;
ALTER TABLE public.output_versions ADD COLUMN IF NOT EXISTS first_published_at timestamptz;

DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'deliveries_publish_target_check' AND conrelid = 'public.deliveries'::regclass
  ) THEN
    ALTER TABLE public.deliveries
      ADD CONSTRAINT deliveries_publish_target_check CHECK (mode <> 'publish' OR target_ref IS NOT NULL);
  END IF;
END
$guard$;

CREATE UNIQUE INDEX IF NOT EXISTS deliveries_active_publish_version_key
  ON public.deliveries (version_id) WHERE mode = 'publish' AND state IN ('publishing', 'published');
CREATE UNIQUE INDEX IF NOT EXISTS deliveries_active_publish_target_key
  ON public.deliveries (target_ref) WHERE mode = 'publish' AND state IN ('publishing', 'published');

-- Starts a publish (§1.2). Returns { kind: 'begun' | 'existing', delivery_id, state }.
-- The allowance is checked here, before Google is called, but nothing is
-- counted: finish counts. already_publishing carries the active delivery's id
-- in the error detail.
CREATE OR REPLACE FUNCTION public.begin_publish_output_version(p_version_id uuid, p_actor uuid, p_target_ref text, p_idempotency_key text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v public.output_versions%rowtype;
  existing public.deliveries%rowtype;
  active_id uuid;
  ws_timezone text;
  ws_tier text;
  usage_period text;
  usage_row public.workspace_usage%rowtype;
  delivery_id uuid;
begin
  -- Same key, same answer: the route can retry without a second delivery.
  select * into existing from public.deliveries where idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object('kind', 'existing', 'delivery_id', existing.id, 'state', existing.state);
  end if;

  select * into v from public.output_versions where id = p_version_id for update;
  if not found then
    raise exception using errcode = 'P0001', message = 'version_not_found';
  end if;
  perform public.offer_current_for_version(v);
  if v.approval_state <> 'approved' then
    raise exception using errcode = 'P0001', message = 'not_approved';
  end if;

  select id into active_id from public.deliveries
  where version_id = v.id and mode = 'publish' and state in ('publishing', 'published');
  if found then
    raise exception using errcode = 'P0001', message = 'already_publishing', detail = active_id::text;
  end if;
  if exists (
    select 1 from public.deliveries
    where target_ref = p_target_ref and mode = 'publish' and state in ('publishing', 'published')
  ) then
    raise exception using errcode = 'P0001', message = 'target_busy';
  end if;

  if v.first_exported_at is null and v.first_published_at is null then
    select timezone, tier into ws_timezone, ws_tier from public.workspaces where id = v.workspace_id;
    usage_period := to_char(now() at time zone coalesce(ws_timezone, 'Asia/Hong_Kong'), 'YYYY-MM');

    -- The same lazy period row as export_output_version (lite 3, paid unlimited).
    insert into public.workspace_usage (workspace_id, period, approved_deliveries, allowance)
    values (v.workspace_id, usage_period, 0, case when ws_tier = 'paid' then null else 3 end)
    on conflict (workspace_id, period) do nothing;

    select * into usage_row from public.workspace_usage
    where workspace_id = v.workspace_id and period = usage_period
    for update;

    if usage_row.allowance is not null and usage_row.approved_deliveries >= usage_row.allowance then
      raise exception using errcode = 'P0001', message = 'allowance_exceeded';
    end if;
  end if;

  insert into public.deliveries (workspace_id, version_id, mode, channel, state, counted, idempotency_key, payload, created_by, target_ref)
  values (v.workspace_id, v.id, 'publish', 'google_business', 'publishing', false, p_idempotency_key,
          jsonb_build_object('version_no', v.version_no), p_actor, p_target_ref)
  returning id into delivery_id;

  update public.output_versions
  set delivery_state = 'publishing'
  where id = v.id;

  insert into public.audit_events (workspace_id, actor_type, actor_id, event, entity_type, entity_id, payload)
  values (v.workspace_id, 'user', p_actor, 'delivery.publish_started', 'delivery', delivery_id,
          jsonb_build_object('version_no', v.version_no, 'version_id', v.id, 'action_id', v.action_id,
                             'idempotency_key', p_idempotency_key));

  return jsonb_build_object('kind', 'begun', 'delivery_id', delivery_id, 'state', 'publishing');
end;
$function$;

REVOKE ALL ON FUNCTION public.begin_publish_output_version(p_version_id uuid, p_actor uuid, p_target_ref text, p_idempotency_key text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.begin_publish_output_version(p_version_id uuid, p_actor uuid, p_target_ref text, p_idempotency_key text) TO sme_app_runtime;

-- Ends a publish (§1.3). Returns { kind: 'finished' | 'existing', state, counted }.
-- A second finisher (reconcile racing publish) gets 'existing' and changes
-- nothing. A verified publish of a never-counted version counts one delivery
-- unconditionally: the allowance was checked at begin and the reply is
-- already public (ruling P2).
CREATE OR REPLACE FUNCTION public.finish_publish_output_version(p_delivery_id uuid, p_actor uuid, p_outcome text, p_receipt jsonb, p_reason text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  d public.deliveries%rowtype;
  v public.output_versions%rowtype;
  counts boolean;
  ws_timezone text;
  ws_tier text;
  usage_period text;
begin
  select * into d from public.deliveries where id = p_delivery_id for update;
  if found and d.mode = 'publish' and d.state in ('published', 'failed') then
    return jsonb_build_object('kind', 'existing', 'state', d.state, 'counted', d.counted);
  end if;
  if not found or d.mode <> 'publish' or d.state <> 'publishing' then
    raise exception using errcode = 'P0001', message = 'delivery_not_publishing';
  end if;
  if p_outcome is null or p_outcome not in ('published', 'failed') then
    raise exception using errcode = 'P0001', message = 'invalid_outcome';
  end if;

  select * into v from public.output_versions where id = d.version_id for update;

  if p_outcome = 'published' then
    counts := v.first_exported_at is null and v.first_published_at is null;

    if counts then
      select timezone, tier into ws_timezone, ws_tier from public.workspaces where id = v.workspace_id;
      usage_period := to_char(now() at time zone coalesce(ws_timezone, 'Asia/Hong_Kong'), 'YYYY-MM');

      -- The period may have turned since begin, so the row is created lazily again.
      insert into public.workspace_usage (workspace_id, period, approved_deliveries, allowance)
      values (v.workspace_id, usage_period, 0, case when ws_tier = 'paid' then null else 3 end)
      on conflict (workspace_id, period) do nothing;

      update public.workspace_usage
      set approved_deliveries = approved_deliveries + 1
      where workspace_id = v.workspace_id and period = usage_period;
    end if;

    update public.deliveries
    set state = 'published',
        counted = counts,
        verified_at = now(),
        provider_receipt = p_receipt
    where id = d.id;

    update public.output_versions
    set first_published_at = coalesce(first_published_at, now()),
        delivery_state = 'published'
    where id = v.id;

    insert into public.audit_events (workspace_id, actor_type, actor_id, event, entity_type, entity_id, payload)
    values (v.workspace_id, 'user', p_actor, 'delivery.published', 'delivery', d.id,
            jsonb_build_object('version_no', v.version_no, 'version_id', v.id, 'action_id', v.action_id,
                               'counted', counts));

    return jsonb_build_object('kind', 'finished', 'state', 'published', 'counted', counts);
  end if;

  update public.deliveries
  set state = 'failed',
      failure_reason = p_reason
  where id = d.id;

  update public.output_versions
  set delivery_state = case when first_exported_at is not null then 'exported' else 'export_ready' end
  where id = v.id;

  insert into public.audit_events (workspace_id, actor_type, actor_id, event, entity_type, entity_id, payload)
  values (v.workspace_id, 'user', p_actor, 'delivery.publish_failed', 'delivery', d.id,
          jsonb_build_object('version_no', v.version_no, 'version_id', v.id, 'action_id', v.action_id,
                             'reason', p_reason));

  return jsonb_build_object('kind', 'finished', 'state', 'failed', 'counted', false);
end;
$function$;

REVOKE ALL ON FUNCTION public.finish_publish_output_version(p_delivery_id uuid, p_actor uuid, p_outcome text, p_receipt jsonb, p_reason text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.finish_publish_output_version(p_delivery_id uuid, p_actor uuid, p_outcome text, p_receipt jsonb, p_reason text) TO sme_app_runtime;

-- Marks a published reply cancelled (§1.4). The owner-only check is the
-- route's. No usage refund: counted and first_published_at stay, so a later
-- re-publish or export of the same version never counts again.
CREATE OR REPLACE FUNCTION public.cancel_published_reply(p_delivery_id uuid, p_actor uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  d public.deliveries%rowtype;
  v public.output_versions%rowtype;
begin
  select * into d from public.deliveries where id = p_delivery_id for update;
  if not found or d.mode <> 'publish' or d.state <> 'published' then
    raise exception using errcode = 'P0001', message = 'delivery_not_published';
  end if;

  select * into v from public.output_versions where id = d.version_id for update;

  update public.deliveries
  set state = 'cancelled'
  where id = d.id;

  update public.output_versions
  set delivery_state = case when first_exported_at is not null then 'exported' else 'cancelled' end
  where id = v.id;

  insert into public.audit_events (workspace_id, actor_type, actor_id, event, entity_type, entity_id, payload)
  values (v.workspace_id, 'user', p_actor, 'delivery.publish_cancelled', 'delivery', d.id,
          jsonb_build_object('version_no', v.version_no, 'version_id', v.id, 'action_id', v.action_id));

  return jsonb_build_object('kind', 'cancelled', 'delivery_id', d.id, 'state', 'cancelled');
end;
$function$;

REVOKE ALL ON FUNCTION public.cancel_published_reply(p_delivery_id uuid, p_actor uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cancel_published_reply(p_delivery_id uuid, p_actor uuid) TO sme_app_runtime;

-- export_output_version from 0011 with exactly these changes (§1.5); nothing
-- else changes: the idempotency return, mode check, offer guard, period, lazy
-- row, audit event name and return shape are byte-for-byte 0011 (pinned by
-- lib/workspace/publish-sql.test.ts).
--   (a) A new local, counts := first_export and v.first_published_at is null.
--       The allowance and usage-increment block runs on counts instead of
--       first_export, and deliveries.counted and the audit counted field use
--       counts.
--   (b) The first_exported_at update still runs on first_export, in its own
--       block, and its delivery_state becomes 'published' when the version is
--       already published, else 'exported', so exporting a published version
--       never downgrades the "verified on Google" state.
--   (c) The return value's counted uses counts.

CREATE OR REPLACE FUNCTION public.export_output_version(p_version_id uuid, p_actor uuid, p_mode text, p_idempotency_key text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v public.output_versions%rowtype;
  existing public.deliveries%rowtype;
  ws_timezone text;
  ws_tier text;
  usage_period text;
  usage_row public.workspace_usage%rowtype;
  first_export boolean;
  counts boolean;
  delivery_id uuid;
begin
  if p_mode not in ('export', 'copy') then
    raise exception using errcode = 'P0001', message = 'invalid_mode';
  end if;

  -- Same key, same answer: the route can retry without a second count.
  select * into existing from public.deliveries where idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object('kind', 'existing', 'delivery_id', existing.id, 'version_id', existing.version_id,
                              'counted', false, 'state', existing.state);
  end if;

  select * into v from public.output_versions where id = p_version_id for update;
  if not found then
    raise exception using errcode = 'P0001', message = 'version_not_found';
  end if;
  perform public.offer_current_for_version(v);
  if v.approval_state <> 'approved' then
    raise exception using errcode = 'P0001', message = 'not_approved';
  end if;

  first_export := v.first_exported_at is null;
  counts := first_export and v.first_published_at is null;

  if counts then
    select timezone, tier into ws_timezone, ws_tier from public.workspaces where id = v.workspace_id;
    usage_period := to_char(now() at time zone coalesce(ws_timezone, 'Asia/Hong_Kong'), 'YYYY-MM');

    -- Lazily create the period row with the tier's allowance (lite 3, paid
    -- unlimited) so the first export of a month never fails for lack of one.
    insert into public.workspace_usage (workspace_id, period, approved_deliveries, allowance)
    values (v.workspace_id, usage_period, 0, case when ws_tier = 'paid' then null else 3 end)
    on conflict (workspace_id, period) do nothing;

    select * into usage_row from public.workspace_usage
    where workspace_id = v.workspace_id and period = usage_period
    for update;

    if usage_row.allowance is not null and usage_row.approved_deliveries >= usage_row.allowance then
      raise exception using errcode = 'P0001', message = 'allowance_exceeded';
    end if;

    update public.workspace_usage
    set approved_deliveries = approved_deliveries + 1
    where workspace_id = v.workspace_id and period = usage_period;
  end if;

  if first_export then
    update public.output_versions
    set first_exported_at = now(),
        delivery_state = case when v.delivery_state = 'published' then 'published' else 'exported' end
    where id = v.id;
  end if;

  insert into public.deliveries (workspace_id, version_id, mode, state, counted, idempotency_key, payload, created_by)
  values (v.workspace_id, v.id, p_mode, 'exported', counts, p_idempotency_key,
          jsonb_build_object('version_no', v.version_no), p_actor)
  returning id into delivery_id;

  insert into public.audit_events (workspace_id, actor_type, actor_id, event, entity_type, entity_id, payload)
  values (v.workspace_id, 'user', p_actor,
          case when p_mode = 'copy' then 'delivery.copied' else 'delivery.exported' end,
          'delivery', delivery_id,
          jsonb_build_object('version_no', v.version_no, 'version_id', v.id, 'action_id', v.action_id,
                             'counted', counts, 'idempotency_key', p_idempotency_key));

  return jsonb_build_object('kind', 'exported', 'delivery_id', delivery_id, 'version_id', v.id,
                            'counted', counts, 'state', 'exported');
end;
$function$;

REVOKE ALL ON FUNCTION public.export_output_version(p_version_id uuid, p_actor uuid, p_mode text, p_idempotency_key text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.export_output_version(p_version_id uuid, p_actor uuid, p_mode text, p_idempotency_key text) TO sme_app_runtime;
$m0014$;

  -- Post-apply checks. A failure raises and rolls everything back.
  SELECT string_agg(c.col, ', ') INTO missing
    FROM (VALUES ('deliveries', 'target_ref'), ('deliveries', 'provider_receipt'), ('deliveries', 'failure_reason'),
                 ('deliveries', 'verified_at'), ('output_versions', 'first_published_at')) AS c(tbl, col)
    WHERE NOT EXISTS (
      SELECT 1 FROM pg_attribute a
      WHERE a.attrelid = ('public.' || c.tbl)::regclass AND a.attname = c.col AND NOT a.attisdropped);
  IF missing IS NOT NULL THEN
    RAISE EXCEPTION 'apply-0014 check failed: missing columns %', missing;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'deliveries_publish_target_check' AND conrelid = 'public.deliveries'::regclass AND contype = 'c'
  ) THEN
    RAISE EXCEPTION 'apply-0014 check failed: deliveries_publish_target_check is missing';
  END IF;

  FOREACH fn IN ARRAY ARRAY['deliveries_active_publish_version_key', 'deliveries_active_publish_target_key'] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_index i
      WHERE i.indexrelid = to_regclass('public.' || fn) AND i.indrelid = 'public.deliveries'::regclass
        AND i.indisunique AND i.indpred IS NOT NULL
    ) THEN
      RAISE EXCEPTION 'apply-0014 check failed: partial unique index % is missing', fn;
    END IF;
  END LOOP;

  FOREACH fn IN ARRAY ARRAY[
    'public.begin_publish_output_version(uuid,uuid,text,text)',
    'public.finish_publish_output_version(uuid,uuid,text,jsonb,text)',
    'public.cancel_published_reply(uuid,uuid)',
    'public.export_output_version(uuid,uuid,text,text)'
  ] LOOP
    SELECT pr.oid, pr.prosecdef, pr.proconfig, pg_get_userbyid(pr.proowner) AS owner,
           has_function_privilege('sme_app_runtime', pr.oid, 'EXECUTE') AS runtime_exec,
           EXISTS (SELECT 1 FROM aclexplode(coalesce(pr.proacl, acldefault('f', pr.proowner))) x
                   WHERE x.grantee = 0 AND x.privilege_type = 'EXECUTE') AS public_exec
      INTO p
      FROM pg_proc pr WHERE pr.oid = to_regprocedure(fn);
    IF p.oid IS NULL THEN
      RAISE EXCEPTION 'apply-0014 check failed: function % is missing', fn;
    END IF;
    IF p.prosecdef OR p.proconfig IS DISTINCT FROM ARRAY['search_path=""'] OR p.owner <> 'smeassistant_migrator'
       OR NOT p.runtime_exec OR p.public_exec THEN
      RAISE EXCEPTION 'apply-0014 check failed: % is not a migrator-owned SECURITY INVOKER function with search_path '''' executable by sme_app_runtime only', fn;
    END IF;
  END LOOP;

  IF (SELECT md5(prosrc) FROM pg_proc WHERE oid = to_regprocedure('public.export_output_version(uuid,uuid,text,text)'))
     IS DISTINCT FROM '33952a4e8f01eb27e5078bfad12163bc' THEN
    RAISE EXCEPTION 'apply-0014 check failed: export_output_version body differs from 0014';
  END IF;

  INSERT INTO neon_migrations.journal(ordinal, name, checksum)
    VALUES (14, '0014_publish_reply.sql', 'e2c181b78e1e2015cf624e4465b0b392b02db2ac74c157f4cb5679e0233097a3');

  RAISE NOTICE 'apply-0014: applied 0014_publish_reply.sql and recorded journal row 14';
END
$apply$;
