-- apply-0015.sql: applies neon/migrations/0015_action_list_indexes.sql (T-12: three
-- read indexes for the owner action list and the latest run/version lookups,
-- action_runs_latest_metadata_idx, output_versions_latest_metadata_idx and
-- actions_list_keyset_idx; no table, column, function or grant changes) to a
-- database whose migration journal holds exactly 0001-0014, and records journal
-- row 15, in one transaction.
--
-- What it does, in order, inside one DO block (one statement, one transaction):
--   1. SET LOCAL ROLE smeassistant_migrator, then refuses unless current_user is
--      that role, so the indexes are built by the role that owns the tables.
--   2. Takes the migration runner's advisory lock, pg_advisory_xact_lock(1936549221, 3)
--      (scripts/neon/migrations.ts).
--   3. Refuses unless neon_migrations.journal is exactly ordinals 1-14, with the
--      names and sha256 checksums of neon/migrations/0001-0014 as loadMigrations()
--      computes them.
--   4. Executes the exact text of 0015_action_list_indexes.sql.
--   5. Checks the result: each of the three indexes exists on its table, is
--      valid, and its pg_get_indexdef equals the definition PostgreSQL 16 reports
--      for a database migrated straight to 0015. 0015 uses CREATE INDEX IF NOT
--      EXISTS, so an index of the same name with a different definition would be
--      kept silently; this check refuses it instead.
--   6. Inserts journal row (15, '0015_action_list_indexes.sql', '61c3ce12d4342181d979e586d9077ef40664f318fa9f5051929f59c3cc3b5763').
-- Any refusal, failed check or error rolls the whole statement back; nothing is
-- changed.
--
-- How to run: in the Neon SQL Editor, logged in as neondb_owner, paste and run
-- this whole file. neondb_owner must hold smeassistant_migrator WITH SET TRUE;
-- without it the statement fails with "permission denied to set role".
-- On success Postgres reports one notice:
-- "apply-0015: applied 0015_action_list_indexes.sql and recorded journal row 15".
--
-- Before running, follow the operator rule in docs/operations/migration-readiness.md:
-- match the Neon compute endpoint and database to Vercel's Production DATABASE_URL,
-- confirm the journal is 1-14, and run docs/operations/check-missing-columns.sql
-- (0 rows). Run it on a Neon test branch of production first, then on production.
--
-- Locking: a plain CREATE INDEX (CONCURRENTLY cannot run inside a transaction)
-- holds a SHARE lock on action_runs, output_versions and actions while each index
-- is built, so writes to those tables wait until the statement commits; reads
-- continue. On today's row counts this takes well under a second. Run it outside
-- busy hours if those tables have grown large.
--
-- Applying it is NOT required by the deployed code: no query depends on these
-- indexes, they only make the action list and the latest run/version lookups
-- cheaper. It changes no data and no behaviour. Rollback, if ever needed, is a
-- separate authorised migration that drops the indexes; never delete journal row 15.
-- 0014 (apply-0014.sql) must already be applied: this statement refuses any
-- other journal. A second run refuses with the journal message and changes
-- nothing.
--
-- Do not edit this file. It was generated from the migration files on disk
-- (neon/migrations/0001-0015); the embedded 0015 text and the checksums must
-- match them byte for byte, or the repository runner will later refuse the
-- journal with migration_checksum_mismatch. tests/rollout-apply-0015.test.ts
-- checks this. It contains no secrets.
DO $apply$
DECLARE
  expected CONSTANT text[] := ARRAY[
    '1 0001_identity.sql f2e65e08e94c6514735db9a7eb6b0dcc5ec522732e2fb3e573b02b62aedb60fa',
    '2 0002_business.sql 34c46b53bc08e12d7c76d365c177877890ebadec27fbf4d7836e253d901021a1',
    '3 0003_workflows.sql b8f80980ab7758ae068bcab9dfea4ae0fcc6cc78b2ed49b6410c92b103a12ab1',
    '4 0004_atomic_operations.sql b24f2cbba79881d1f97118e05a5d7990a847fdaed6ecd5461682f404af076069',
    '5 0005_owner_removal_guard.sql c4349d2ba9a24a595b37ed547574e8231ee5ff0eb717ef8ffa5fad1fa093c26b',
    '6 0006_action_applications.sql ea0f7471c0b469a5e99b884557224b542b920a0aadc7f1f49223697334a4be47',
    '7 0007_action_verification.sql e9f8132aa98021c7f2861b9e3fdc2e0f3847445b91ee955683ce696770f43d11',
    '8 0008_workspace_internal.sql f9f03d6c1d70231871e2e683c9318c98f55afbd0fd125a43e712d328f019d678',
    '9 0009_scan_attempts.sql 3c35ab9965be1d4821e885a2e43676c743e62f25435e4d59bd46d2c34a3d1768',
    '10 0010_mail_outbox.sql ec50dceefbc20b2acbf14cf8908a550bc5c65e9feda346fd57338f1e0edce69c',
    '11 0011_offers.sql 5d5a01b5796f579884de31b31aece3d54159f0b42a06042f7b228b93b0eb9449',
    '12 0012_work_packs.sql e7933f6caac57dbc7384aae24c0fd86316cf3b521167432fe483df58cc9b7289',
    '13 0013_preview_events.sql 98ec68e18a5281885ac12497af8328c3c7300ce7adfd1869f74f62912160cf24',
    '14 0014_publish_reply.sql e2c181b78e1e2015cf624e4465b0b392b02db2ac74c157f4cb5679e0233097a3'
  ];
  expected_defs CONSTANT text[] := ARRAY[
    ARRAY['action_runs_latest_metadata_idx', 'public.action_runs', 'CREATE INDEX action_runs_latest_metadata_idx ON public.action_runs USING btree (workspace_id, action_id, created_at DESC, id DESC) INCLUDE (state)'],
    ARRAY['output_versions_latest_metadata_idx', 'public.output_versions', 'CREATE INDEX output_versions_latest_metadata_idx ON public.output_versions USING btree (workspace_id, action_id, version_no DESC, id DESC) INCLUDE (approval_state, delivery_state, first_exported_at)'],
    ARRAY['actions_list_keyset_idx', 'public.actions', 'CREATE INDEX actions_list_keyset_idx ON public.actions USING btree (workspace_id, COALESCE(priority_score, (0)::numeric) DESC, updated_at DESC, id DESC) INCLUDE (location_id, action_state, template_key)']
  ];
  found text[];
  ix text[];
  actual text;
BEGIN
  SET LOCAL ROLE smeassistant_migrator;
  IF current_user::text <> 'smeassistant_migrator' THEN
    RAISE EXCEPTION 'apply-0015 refused: running as %, not smeassistant_migrator', current_user;
  END IF;

  PERFORM pg_advisory_xact_lock(1936549221, 3);

  SELECT coalesce(array_agg(ordinal::text || ' ' || name || ' ' || checksum ORDER BY ordinal), ARRAY[]::text[])
    INTO found
    FROM neon_migrations.journal;
  IF found IS DISTINCT FROM expected THEN
    RAISE EXCEPTION 'apply-0015 refused: neon_migrations.journal is not exactly 0001-0014 with the expected checksums (it has % rows)', cardinality(found);
  END IF;

  EXECUTE $m0015$-- T-12: measured 1000-action fixture showed one workspace-wide action_runs
-- bitmap scan per action (about 1 ms each). Latest metadata must use the exact
-- tenant/action equality prefix and deterministic ordering, without body/meta.
-- New migration after verified 0014; only disposable DB execution is authorized.
CREATE INDEX IF NOT EXISTS action_runs_latest_metadata_idx
  ON public.action_runs (workspace_id, action_id, created_at DESC, id DESC)
  INCLUDE (state);

CREATE INDEX IF NOT EXISTS output_versions_latest_metadata_idx
  ON public.output_versions (workspace_id, action_id, version_no DESC, id DESC)
  INCLUDE (approval_state, delivery_state, first_exported_at);

CREATE INDEX IF NOT EXISTS actions_list_keyset_idx
  ON public.actions (workspace_id, (COALESCE(priority_score, 0)) DESC, updated_at DESC, id DESC)
  INCLUDE (location_id, action_state, template_key);
$m0015$;

  FOREACH ix SLICE 1 IN ARRAY expected_defs LOOP
    SELECT pg_get_indexdef(i.indexrelid) INTO actual
      FROM pg_index i
      WHERE i.indexrelid = to_regclass('public.' || ix[1]) AND i.indrelid = to_regclass(ix[2]) AND i.indisvalid;
    IF actual IS NULL THEN
      RAISE EXCEPTION 'apply-0015 check failed: index % on % is missing or invalid', ix[1], ix[2];
    END IF;
    IF actual IS DISTINCT FROM ix[3] THEN
      RAISE EXCEPTION 'apply-0015 check failed: index % exists with a different definition: %', ix[1], actual;
    END IF;
  END LOOP;

  INSERT INTO neon_migrations.journal(ordinal, name, checksum)
    VALUES (15, '0015_action_list_indexes.sql', '61c3ce12d4342181d979e586d9077ef40664f318fa9f5051929f59c3cc3b5763');

  RAISE NOTICE 'apply-0015: applied 0015_action_list_indexes.sql and recorded journal row 15';
END
$apply$;
