-- apply-0009.sql: applies neon/migrations/0009_scan_attempts.sql (P3.5a spend
-- budgets) to a database whose migration journal holds exactly 0001-0008, and
-- records journal row 9, in one transaction.
--
-- What it does, in order, inside one DO block (one statement, one transaction):
--   1. SET LOCAL ROLE smeassistant_migrator, then refuses unless current_user is
--      that role, so every object 0009 creates is owned by the migrator.
--   2. Takes the migration runner's advisory lock, pg_advisory_xact_lock(1936549221, 3)
--      (scripts/neon/migrations.ts).
--   3. Refuses unless neon_migrations.journal is exactly ordinals 1-8, with the
--      names and sha256 checksums of neon/migrations/0001-0008 as loadMigrations()
--      computes them.
--   4. Executes the exact text of 0009_scan_attempts.sql.
--   5. Inserts journal row (9, '0009_scan_attempts.sql', '3c35ab9965be1d4821e885a2e43676c743e62f25435e4d59bd46d2c34a3d1768').
-- Any refusal or error rolls the whole statement back; nothing is changed.
--
-- How to run: in the Neon SQL Editor, logged in as neondb_owner, paste and run
-- this whole file. neondb_owner must hold smeassistant_migrator WITH SET TRUE;
-- without it the statement fails with "permission denied to set role".
-- On success Postgres reports two notices: policy "server_application" ...
-- does not exist, skipping (0009 drops the policy before creating it), then
-- "apply-0009: applied 0009_scan_attempts.sql and recorded journal row 9".
--
-- Run it on a Neon test branch of production first. Then run it on production,
-- before deploying the P3.5a code: the new scan claim writes to scan_attempts,
-- so every scan fails until this table exists. A second run refuses with the
-- journal message and changes nothing.
--
-- Do not edit this file. It was generated from the migration files on disk
-- (neon/migrations/0001-0009); the embedded 0009 text and the checksums must
-- match them byte for byte, or the repository runner will later refuse the
-- journal with migration_checksum_mismatch. It contains no secrets.
DO $apply$
DECLARE
  expected CONSTANT text[] := ARRAY[
    '1 0001_identity.sql f2e65e08e94c6514735db9a7eb6b0dcc5ec522732e2fb3e573b02b62aedb60fa',
    '2 0002_business.sql 34c46b53bc08e12d7c76d365c177877890ebadec27fbf4d7836e253d901021a1',
    '3 0003_workflows.sql b8f80980ab7758ae068bcab9dfea4ae0fcc6cc78b2ed49b6410c92b103a12ab1',
    '4 0004_atomic_operations.sql b24f2cbba79881d1f97118e05a5d7990a847fdaed6ecd5461682f404af076069',
    '5 0005_owner_removal_guard.sql c4349d2ba9a24a595b37ed547574e8231ee5ff0eb717ef8ffa5fad1fa093c26b',
    '6 0006_action_applications.sql ea0f7471c0b469a5e99b884557224b542b920a0aadc7f1f49223697334a4be47',
    '7 0007_action_verification.sql e9f8132aa98021c7f2861b9e3fdc2e0f3847445b91ee955683ce696770f43d11',
    '8 0008_workspace_internal.sql f9f03d6c1d70231871e2e683c9318c98f55afbd0fd125a43e712d328f019d678'
  ];
  found text[];
BEGIN
  SET LOCAL ROLE smeassistant_migrator;
  IF current_user::text <> 'smeassistant_migrator' THEN
    RAISE EXCEPTION 'apply-0009 refused: running as %, not smeassistant_migrator', current_user;
  END IF;

  PERFORM pg_advisory_xact_lock(1936549221, 3);

  SELECT coalesce(array_agg(ordinal::text || ' ' || name || ' ' || checksum ORDER BY ordinal), ARRAY[]::text[])
    INTO found
    FROM neon_migrations.journal;
  IF found IS DISTINCT FROM expected THEN
    RAISE EXCEPTION 'apply-0009 refused: neon_migrations.journal is not exactly 0001-0008 with the expected checksums (it has % rows)', cardinality(found);
  END IF;

  EXECUTE $m0009$-- P3.5a spend budgets (docs/superpowers/specs/2026-09-25-spend-budgets-design.md).
--
-- One row per scan claim, written by the claim statement itself
-- (lib/budgets/scan.ts BUDGETED_CLAIM_SQL), so a claim cannot happen without
-- its row and a row cannot exist without its claim. audit_jobs keeps only the
-- latest attempt time, so past attempts in a window could not be rebuilt
-- from existing rows.
--
-- ON DELETE CASCADE on the job: attempts are the job's own cost history.
-- ON DELETE SET NULL on the workspace: the global count must keep attempts
-- from deleted workspaces.
CREATE TABLE IF NOT EXISTS public.scan_attempts (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id       uuid NOT NULL REFERENCES public.audit_jobs(id) ON DELETE CASCADE,
  workspace_id uuid REFERENCES public.workspaces(id) ON DELETE SET NULL,
  attempted_at timestamptz NOT NULL DEFAULT now()
);

-- The global and per-workspace rolling-window counts.
CREATE INDEX IF NOT EXISTS scan_attempts_attempted_idx ON public.scan_attempts (attempted_at);
CREATE INDEX IF NOT EXISTS scan_attempts_workspace_idx ON public.scan_attempts (workspace_id, attempted_at);

-- The AI spend sum over recorded action_runs.cost_usd; action_runs had no index.
CREATE INDEX IF NOT EXISTS action_runs_created_idx ON public.action_runs (created_at);
CREATE INDEX IF NOT EXISTS action_runs_workspace_created_idx ON public.action_runs (workspace_id, created_at);

-- RLS, grants and the server-only policy exactly as 0006 does for
-- action_applications. The policy is dropped first so the file is re-runnable
-- (CREATE POLICY has no IF NOT EXISTS).
ALTER TABLE public.scan_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.scan_attempts FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.scan_attempts TO sme_app_runtime;
DROP POLICY IF EXISTS server_application ON public.scan_attempts;
CREATE POLICY server_application ON public.scan_attempts FOR ALL TO sme_app_runtime USING (true) WITH CHECK (true);
$m0009$;

  INSERT INTO neon_migrations.journal(ordinal, name, checksum)
    VALUES (9, '0009_scan_attempts.sql', '3c35ab9965be1d4821e885a2e43676c743e62f25435e4d59bd46d2c34a3d1768');

  RAISE NOTICE 'apply-0009: applied 0009_scan_attempts.sql and recorded journal row 9';
END
$apply$;
