-- apply-0013.sql: applies neon/migrations/0013_preview_events.sql (P4.5 unsaved
-- preview draft: the preview_events table, its three indexes, RLS, the
-- server_application policy and the sme_app_runtime grants, and the two
-- SECURITY INVOKER functions claim_preview_slot and finish_preview_slot, EXECUTE
-- granted to sme_app_runtime only) to a database whose migration journal holds
-- exactly 0001-0012, and records journal row 13, in one transaction.
--
-- What it does, in order, inside one DO block (one statement, one transaction):
--   1. SET LOCAL ROLE smeassistant_migrator, then refuses unless current_user is
--      that role, so every object 0013 creates is owned by the migrator.
--   2. Takes the migration runner's advisory lock, pg_advisory_xact_lock(1936549221, 3)
--      (scripts/neon/migrations.ts).
--   3. Refuses unless neon_migrations.journal is exactly ordinals 1-12, with the
--      names and sha256 checksums of neon/migrations/0001-0012 as loadMigrations()
--      computes them.
--   4. Executes the exact text of 0013_preview_events.sql.
--   5. Inserts journal row (13, '0013_preview_events.sql', '122fc89ecf60732287c51b0970de0aff90785373f38fc341050039d166723467').
-- Any refusal or error rolls the whole statement back; nothing is changed.
--
-- How to run: in the Neon SQL Editor, logged in as neondb_owner, paste and run
-- this whole file. neondb_owner must hold smeassistant_migrator WITH SET TRUE;
-- without it the statement fails with "permission denied to set role".
-- On success Postgres reports two notices: policy "server_application" for
-- relation "public.preview_events" does not exist, skipping (0013 drops the
-- policy before creating it), then
-- "apply-0013: applied 0013_preview_events.sql and recorded journal row 13".
--
-- Run it on a Neon test branch of production first, then on production.
-- Applying it is NOT required before deploying the P4.5 code: while
-- PREVIEW_DRAFT_ENABLED is unset the report card and the /start page and route
-- check the flag first and issue no SQL at all
-- (test/integration/neon-preview-flag-off.integration.test.ts proves it against
-- a database without 0013). It IS required before setting
-- PREVIEW_DRAFT_ENABLED=true: with the flag on and no 0013 every preview request
-- answers "unavailable". The change is purely additive: one new table and two
-- new functions, nothing existing is altered, so applying it ahead of the deploy
-- changes nothing for owners or visitors.
-- 0012 (apply-0012.sql) must already be applied: this statement refuses any
-- other journal. A second run refuses with the journal message and changes
-- nothing.
--
-- Do not edit this file. It was generated from the migration files on disk
-- (neon/migrations/0001-0013); the embedded 0013 text and the checksums must
-- match them byte for byte, or the repository runner will later refuse the
-- journal with migration_checksum_mismatch. It contains no secrets.
DO $apply$
DECLARE
  expected CONSTANT text[] := ARRAY[
    '1 0001_identity.sql f2e65e08e94c6514735db9a7eb6b0dcc5ec522732e2fb3e573b02b62aedb60fa',
    '2 0002_business.sql 34c46b53bc08e12d7c76d365c177877890ebadec27fbf4d7836e253d901021a1',
    '3 0003_workflows.sql b8f80980ab7758ae068bcab9dfea4ae0fcc6cc78b2ed49b6410c92b103a12ab1',
    '4 0004_atomic_operations.sql b24f2cbba79881d1f97118e05a5d7990a847fdaed6ecd5461682f404af076069',
    '5 0005_owner_removal_guard.sql c4349d2ba9a24a595b37ed547574e8231ee5ff0eb717ef8ffa5fad1fa093c26b',
    '6 0006_action_applications.sql ea0f7471c0b469a5e99b884557224b542b920a0aadc7f1f49223697334a4be47',
    '7 0007_action_verification.sql e9f8132aa98021c7f2861b9e3fdc2e0f3847445b91ee955683ce696770f43d11',
    '8 0008_workspace_internal.sql f9f03d6c1d70231871e2e683c9318c98f55afbd0fd125a43e712d328f019d678',
    '9 0009_scan_attempts.sql 3c35ab9965be1d4821e885a2e43676c743e62f25435e4d59bd46d2c34a3d1768',
    '10 0010_mail_outbox.sql ec50dceefbc20b2acbf14cf8908a550bc5c65e9feda346fd57338f1e0edce69c',
    '11 0011_offers.sql 5d5a01b5796f579884de31b31aece3d54159f0b42a06042f7b228b93b0eb9449',
    '12 0012_work_packs.sql e7933f6caac57dbc7384aae24c0fd86316cf3b521167432fe483df58cc9b7289'
  ];
  found text[];
BEGIN
  SET LOCAL ROLE smeassistant_migrator;
  IF current_user::text <> 'smeassistant_migrator' THEN
    RAISE EXCEPTION 'apply-0013 refused: running as %, not smeassistant_migrator', current_user;
  END IF;

  PERFORM pg_advisory_xact_lock(1936549221, 3);

  SELECT coalesce(array_agg(ordinal::text || ' ' || name || ' ' || checksum ORDER BY ordinal), ARRAY[]::text[])
    INTO found
    FROM neon_migrations.journal;
  IF found IS DISTINCT FROM expected THEN
    RAISE EXCEPTION 'apply-0013 refused: neon_migrations.journal is not exactly 0001-0012 with the expected checksums (it has % rows)', cardinality(found);
  END IF;

  EXECUTE $m0013$-- P4.5 unsaved preview draft (docs/superpowers/specs/2026-10-04-preview-draft-design.md, 1.1-1.3).
--
-- A visitor who unlocked a report may get one AI review-reply draft that is
-- never stored. preview_events is the only thing the preview writes: an event
-- ledger with no text column at all (no review, reply, prompt, contact detail
-- or raw IP). ip_hash is the existing HMAC request fingerprint.
--
-- job_id cascades, so erasing a job erases its preview trail. grant_id is SET
-- NULL, so revoking or deleting a grant keeps the cost record.
--
-- Limits live in claim_preview_slot, under one global advisory lock, so
-- concurrent claims are fully serialized (volume is bounded by the daily
-- limit). Only 'claimed' and 'generated' rows count toward the per-grant,
-- per-job and daily limits; 'failed' rows release the slot and 'refused' rows
-- record the refusal. The budget sums cost_usd over every row of the last 24
-- hours, whatever its outcome.
--
-- Both functions are SECURITY INVOKER, like 0004 and 0011 (neon/README.md):
-- the runtime already has RLS-backed DML on preview_events, so no owner
-- elevation is needed.
CREATE TABLE IF NOT EXISTS public.preview_events (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id      uuid NOT NULL REFERENCES public.audit_jobs(id) ON DELETE CASCADE,
  grant_id    uuid REFERENCES public.report_access_grants(id) ON DELETE SET NULL,
  outcome     text NOT NULL,
  reason      text,
  cost_usd    numeric NOT NULL DEFAULT 0,
  ip_hash     text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  CONSTRAINT preview_events_outcome_check CHECK (outcome IN ('claimed', 'generated', 'failed', 'refused')),
  CONSTRAINT preview_events_cost_check CHECK (cost_usd >= 0)
);

CREATE INDEX IF NOT EXISTS preview_events_grant_idx ON public.preview_events (grant_id);
CREATE INDEX IF NOT EXISTS preview_events_job_idx ON public.preview_events (job_id);
CREATE INDEX IF NOT EXISTS preview_events_created_idx ON public.preview_events (created_at);

ALTER TABLE public.preview_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.preview_events FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.preview_events TO sme_app_runtime;
DROP POLICY IF EXISTS server_application ON public.preview_events;
CREATE POLICY server_application ON public.preview_events FOR ALL TO sme_app_runtime USING (true) WITH CHECK (true);

-- Returns { "allowed": true, "event_id": <uuid> } or { "allowed": false, "reason": <r> }.
-- The refusal order is the spec's: already_used, job_limit, daily_limit, budget.
-- Null arguments or non-positive limits raise (22023) rather than allow.
CREATE OR REPLACE FUNCTION public.claim_preview_slot(p_job uuid, p_grant uuid, p_ip_hash text, p_global_daily integer, p_usd_daily numeric)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  refusal text;
  new_event_id uuid;
begin
  if p_job is null or p_grant is null then
    raise exception using errcode = '22023', message = 'preview_claim_target_required';
  end if;
  if p_global_daily is null or p_global_daily < 1 or p_usd_daily is null or p_usd_daily <= 0 then
    raise exception using errcode = '22023', message = 'preview_claim_limits_invalid';
  end if;

  -- One global lock: every claim is serialized, so each check below reads the
  -- committed result of the previous claim.
  perform pg_advisory_xact_lock(hashtextextended('preview_slot', 0));

  -- A crashed request cannot hold a slot.
  update public.preview_events
  set outcome = 'failed',
      reason = 'stale',
      finished_at = now()
  where outcome = 'claimed'
    and created_at < now() - interval '5 minutes';

  if exists (
    select 1 from public.preview_events
    where grant_id = p_grant and outcome in ('claimed', 'generated')
  ) then
    refusal := 'already_used';
  elsif (
    select count(*) from public.preview_events
    where job_id = p_job and outcome in ('claimed', 'generated')
  ) >= 3 then
    refusal := 'job_limit';
  elsif (
    select count(*) from public.preview_events
    where outcome in ('claimed', 'generated') and created_at > now() - interval '24 hours'
  ) >= p_global_daily then
    refusal := 'daily_limit';
  elsif (
    select coalesce(sum(cost_usd), 0) from public.preview_events
    where created_at > now() - interval '24 hours'
  ) >= p_usd_daily then
    refusal := 'budget';
  end if;

  if refusal is not null then
    insert into public.preview_events (job_id, grant_id, outcome, reason, ip_hash)
    values (p_job, p_grant, 'refused', refusal, p_ip_hash);
    return jsonb_build_object('allowed', false, 'reason', refusal);
  end if;

  insert into public.preview_events (job_id, grant_id, outcome, ip_hash)
  values (p_job, p_grant, 'claimed', p_ip_hash)
  returning id into new_event_id;
  return jsonb_build_object('allowed', true, 'event_id', new_event_id);
end;
$function$;

REVOKE ALL ON FUNCTION public.claim_preview_slot(p_job uuid, p_grant uuid, p_ip_hash text, p_global_daily integer, p_usd_daily numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_preview_slot(p_job uuid, p_grant uuid, p_ip_hash text, p_global_daily integer, p_usd_daily numeric) TO sme_app_runtime;

-- Moves a still-claimed row to generated or failed. Any other transition (an
-- unknown event, or a row already generated, failed, stale or refused) is a
-- no-op. An outcome other than generated or failed raises (22023).
CREATE OR REPLACE FUNCTION public.finish_preview_slot(p_event uuid, p_outcome text, p_reason text, p_cost numeric)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if p_outcome is null or p_outcome not in ('generated', 'failed') then
    raise exception using errcode = '22023', message = 'preview_outcome_invalid';
  end if;

  update public.preview_events
  set outcome = p_outcome,
      reason = p_reason,
      cost_usd = p_cost,
      finished_at = now()
  where id = p_event
    and outcome = 'claimed';
end;
$function$;

REVOKE ALL ON FUNCTION public.finish_preview_slot(p_event uuid, p_outcome text, p_reason text, p_cost numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.finish_preview_slot(p_event uuid, p_outcome text, p_reason text, p_cost numeric) TO sme_app_runtime;
$m0013$;

  INSERT INTO neon_migrations.journal(ordinal, name, checksum)
    VALUES (13, '0013_preview_events.sql', '122fc89ecf60732287c51b0970de0aff90785373f38fc341050039d166723467');

  RAISE NOTICE 'apply-0013: applied 0013_preview_events.sql and recorded journal row 13';
END
$apply$;
