-- apply-0012.sql: applies neon/migrations/0012_work_packs.sql (P4.2 work packs:
-- the work_packs and work_pack_items tables, their open-pack unique index, RLS,
-- the server_application policies and the sme_app_runtime grants) to a database
-- whose migration journal holds exactly 0001-0011, and records journal row 12,
-- in one transaction.
--
-- What it does, in order, inside one DO block (one statement, one transaction):
--   1. SET LOCAL ROLE smeassistant_migrator, then refuses unless current_user is
--      that role, so every object 0012 creates is owned by the migrator.
--   2. Takes the migration runner's advisory lock, pg_advisory_xact_lock(1936549221, 3)
--      (scripts/neon/migrations.ts).
--   3. Refuses unless neon_migrations.journal is exactly ordinals 1-11, with the
--      names and sha256 checksums of neon/migrations/0001-0011 as loadMigrations()
--      computes them.
--   4. Executes the exact text of 0012_work_packs.sql.
--   5. Inserts journal row (12, '0012_work_packs.sql', 'e7933f6caac57dbc7384aae24c0fd86316cf3b521167432fe483df58cc9b7289').
-- Any refusal or error rolls the whole statement back; nothing is changed.
--
-- How to run: in the Neon SQL Editor, logged in as neondb_owner, paste and run
-- this whole file. neondb_owner must hold smeassistant_migrator WITH SET TRUE;
-- without it the statement fails with "permission denied to set role".
-- On success Postgres reports three notices: policy "server_application" for
-- relation "public.work_packs" does not exist, skipping, the same for
-- "public.work_pack_items" (0012 drops each policy before creating it), then
-- "apply-0012: applied 0012_work_packs.sql and recorded journal row 12".
--
-- Run it on a Neon test branch of production first, then on production. Unlike
-- 0011, applying it is NOT required before deploying the P4.2 code: while
-- WORK_PACKS_ENABLED is unset no code path reads or writes work_packs or
-- work_pack_items (test/integration/neon-work-packs-flag-off.integration.test.ts
-- proves it against a database without 0012). It IS required before setting
-- WORK_PACKS_ENABLED=true: with the flag on and no 0012 the pack card and pack
-- routes fail. The change is purely additive: two new tables, nothing existing is
-- altered, so applying it ahead of the deploy changes nothing for owners.
-- 0011 (apply-0011.sql) must already be applied: this statement refuses any
-- other journal. A second run refuses with the journal message and changes
-- nothing.
--
-- Do not edit this file. It was generated from the migration files on disk
-- (neon/migrations/0001-0012); the embedded 0012 text and the checksums must
-- match them byte for byte, or the repository runner will later refuse the
-- journal with migration_checksum_mismatch. It contains no secrets.
DO $apply$
DECLARE
  expected CONSTANT text[] := ARRAY[
    '1 0001_identity.sql f2e65e08e94c6514735db9a7eb6b0dcc5ec522732e2fb3e573b02b62aedb60fa',
    '2 0002_business.sql 34c46b53bc08e12d7c76d365c177877890ebadec27fbf4d7836e253d901021a1',
    '3 0003_workflows.sql b8f80980ab7758ae068bcab9dfea4ae0fcc6cc78b2ed49b6410c92b103a12ab1',
    '4 0004_atomic_operations.sql b24f2cbba79881d1f97118e05a5d7990a847fdaed6ecd5461682f404af076069',
    '5 0005_owner_removal_guard.sql c4349d2ba9a24a595b37ed547574e8231ee5ff0eb717ef8ffa5fad1fa093c26b',
    '6 0006_action_applications.sql ea0f7471c0b469a5e99b884557224b542b920a0aadc7f1f49223697334a4be47',
    '7 0007_action_verification.sql e9f8132aa98021c7f2861b9e3fdc2e0f3847445b91ee955683ce696770f43d11',
    '8 0008_workspace_internal.sql f9f03d6c1d70231871e2e683c9318c98f55afbd0fd125a43e712d328f019d678',
    '9 0009_scan_attempts.sql 3c35ab9965be1d4821e885a2e43676c743e62f25435e4d59bd46d2c34a3d1768',
    '10 0010_mail_outbox.sql ec50dceefbc20b2acbf14cf8908a550bc5c65e9feda346fd57338f1e0edce69c',
    '11 0011_offers.sql 5d5a01b5796f579884de31b31aece3d54159f0b42a06042f7b228b93b0eb9449'
  ];
  found text[];
BEGIN
  SET LOCAL ROLE smeassistant_migrator;
  IF current_user::text <> 'smeassistant_migrator' THEN
    RAISE EXCEPTION 'apply-0012 refused: running as %, not smeassistant_migrator', current_user;
  END IF;

  PERFORM pg_advisory_xact_lock(1936549221, 3);

  SELECT coalesce(array_agg(ordinal::text || ' ' || name || ' ' || checksum ORDER BY ordinal), ARRAY[]::text[])
    INTO found
    FROM neon_migrations.journal;
  IF found IS DISTINCT FROM expected THEN
    RAISE EXCEPTION 'apply-0012 refused: neon_migrations.journal is not exactly 0001-0011 with the expected checksums (it has % rows)', cardinality(found);
  END IF;

  EXECUTE $m0012$-- P4.2 work packs (docs/superpowers/specs/2026-10-02-work-packs-design.md, 1.1, 1.2).
--
-- A work pack groups the actions a workspace starts together (today only the
-- "visibility starter": review-response, visibility-content, website-basics).
-- It is a grouping, not a ledger: no approval, delivery, run or output column
-- exists here. Each item's status is always derived from its action, the latest
-- run and the latest version, so there is no second source of truth.
--
-- At most one OPEN pack per (workspace, location, kind). The unique index
-- below is what makes "Start pack" idempotent under concurrency; a null
-- location_id is coalesced to the all-zero uuid so a workspace-wide pack is
-- unique too (a plain unique index would treat nulls as distinct).
--
-- work_packs cascade from workspaces and locations: a pack is about one
-- workspace's location and is meaningless without them. work_pack_items cascade
-- from their pack, but action_id is NO ACTION on purpose (like actions.offer_id
-- in 0011): deleting an action a pack still points to fails (23503), while
-- deleting a workspace still removes packs, items and actions. The action FK is
-- DEFERRABLE INITIALLY DEFERRED because a workspace delete cascades to actions
-- before it reaches the pack items (actions is the older table, so its cascade
-- trigger fires first); an immediate NO ACTION check would fail that cascade
-- while the items still exist. Deferred, the check runs at commit, by which
-- point the cascade has removed the items too.
CREATE TABLE IF NOT EXISTS public.work_packs (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  location_id  uuid REFERENCES public.locations(id) ON DELETE CASCADE,
  kind         text NOT NULL,
  created_by   uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  closed_at    timestamptz,
  CONSTRAINT work_packs_kind_check CHECK (kind IN ('visibility_starter'))
);

CREATE UNIQUE INDEX IF NOT EXISTS work_packs_open_idx
  ON public.work_packs (workspace_id, coalesce(location_id, '00000000-0000-0000-0000-000000000000'::uuid), kind)
  WHERE closed_at IS NULL;

CREATE TABLE IF NOT EXISTS public.work_pack_items (
  pack_id      uuid NOT NULL REFERENCES public.work_packs(id) ON DELETE CASCADE,
  action_id    uuid NOT NULL CONSTRAINT work_pack_items_action_id_fkey REFERENCES public.actions(id) DEFERRABLE INITIALLY DEFERRED,
  template_key text NOT NULL,
  position     smallint NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT work_pack_items_pkey PRIMARY KEY (pack_id, template_key),
  CONSTRAINT work_pack_items_template_check CHECK (template_key IN ('review-response', 'visibility-content', 'website-basics')),
  CONSTRAINT work_pack_items_position_check CHECK (position BETWEEN 1 AND 3)
);

CREATE INDEX IF NOT EXISTS work_pack_items_action_idx ON public.work_pack_items (action_id);

ALTER TABLE public.work_packs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.work_packs FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.work_packs TO sme_app_runtime;
DROP POLICY IF EXISTS server_application ON public.work_packs;
CREATE POLICY server_application ON public.work_packs FOR ALL TO sme_app_runtime USING (true) WITH CHECK (true);

ALTER TABLE public.work_pack_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.work_pack_items FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.work_pack_items TO sme_app_runtime;
DROP POLICY IF EXISTS server_application ON public.work_pack_items;
CREATE POLICY server_application ON public.work_pack_items FOR ALL TO sme_app_runtime USING (true) WITH CHECK (true);
$m0012$;

  INSERT INTO neon_migrations.journal(ordinal, name, checksum)
    VALUES (12, '0012_work_packs.sql', 'e7933f6caac57dbc7384aae24c0fd86316cf3b521167432fe483df58cc9b7289');

  RAISE NOTICE 'apply-0012: applied 0012_work_packs.sql and recorded journal row 12';
END
$apply$;
