-- reconcile-journal-0009-0015.sql: records journal rows 9-15 on a database whose
-- schema already matches neon/migrations/0001-0015 but whose neon_migrations.journal
-- stops at 0008. It changes NO schema object and NO application row; it only inserts
-- the seven missing journal rows, after proving the schema is exactly what 0015 leaves.
--
-- Why it exists (2026-10-10, docs/operations/migration-readiness.md): production
-- (project morning-hill-92255530, branch br-wandering-field-azdc91yj, endpoint
-- ep-tiny-forest-azzm8bni, database neondb) has every table, column, index,
-- constraint, function, grant and trigger of 0009-0015, identical to a branch
-- migrated by the repository runner, but its journal holds only 0001-0008. The
-- 0009-0014 objects there are owned by neondb_owner, so they were not created by the
-- apply-00NN statements (those run as smeassistant_migrator and write the journal).
-- With journal 8, every apply-00NN statement, pnpm neon:readiness and any future
-- migration refuse that database.
--
-- What it does, in order, inside one DO block (one statement, one transaction):
--   1. SET LOCAL ROLE smeassistant_migrator, then refuses unless current_user is
--      that role (the role that writes the journal in every apply statement).
--   2. Takes the migration runner's advisory lock, pg_advisory_xact_lock(1936549221, 3).
--   3. Refuses unless neon_migrations.journal is exactly ordinals 1-8 with the names
--      and sha256 checksums of neon/migrations/0001-0008.
--   4. Computes an owner-free fingerprint of the public schema in eight categories
--      (tables and RLS; columns with type, NOT NULL and default; index definitions;
--      constraint definitions; functions with body md5, SECURITY, search_path and
--      EXECUTE for sme_app_runtime / PUBLIC; table privileges of sme_app_runtime;
--      triggers; types) and refuses, naming every category that differs, unless all
--      eight equal the values PostgreSQL 18.6 reports for a database migrated straight
--      to 0015 by scripts/neon/migrations.ts. Object owners are deliberately not part
--      of the fingerprint (see above); this statement does not change them.
--   5. Inserts journal rows 9-15 with the names and sha256 checksums of the committed
--      migration files, exactly as the repository runner would have.
-- Any refusal, failed check or error rolls the whole statement back; nothing is changed.
--
-- How to run: only after the owner has approved it for this specific database. In the
-- Neon SQL Editor, project Smeassistant, branch production, database neondb, logged in
-- as neondb_owner: paste and run this whole file. On success Postgres reports one notice:
-- "reconcile-journal: schema matches 0015; recorded journal rows 9-15".
-- Afterwards SELECT max(ordinal) FROM neon_migrations.journal returns 15, and
-- apply-0015.sql refuses (its work is already done).
--
-- Do NOT run it on a database whose journal is not exactly 1-8 (it refuses), and never
-- edit it to make it pass: a fingerprint mismatch means the schema is not 0015 and the
-- journal must not claim it is. A second run refuses with the journal message.
--
-- Do not edit this file. It was generated from the migration files on disk
-- (neon/migrations/0001-0015) and a disposable PostgreSQL 18.6;
-- tests/rollout-reconcile-journal.test.ts checks the journal names and checksums.
-- It contains no secrets.
DO $reconcile$
DECLARE
  expected_journal CONSTANT text[] := ARRAY[
    '1 0001_identity.sql f2e65e08e94c6514735db9a7eb6b0dcc5ec522732e2fb3e573b02b62aedb60fa',
    '2 0002_business.sql 34c46b53bc08e12d7c76d365c177877890ebadec27fbf4d7836e253d901021a1',
    '3 0003_workflows.sql b8f80980ab7758ae068bcab9dfea4ae0fcc6cc78b2ed49b6410c92b103a12ab1',
    '4 0004_atomic_operations.sql b24f2cbba79881d1f97118e05a5d7990a847fdaed6ecd5461682f404af076069',
    '5 0005_owner_removal_guard.sql c4349d2ba9a24a595b37ed547574e8231ee5ff0eb717ef8ffa5fad1fa093c26b',
    '6 0006_action_applications.sql ea0f7471c0b469a5e99b884557224b542b920a0aadc7f1f49223697334a4be47',
    '7 0007_action_verification.sql e9f8132aa98021c7f2861b9e3fdc2e0f3847445b91ee955683ce696770f43d11',
    '8 0008_workspace_internal.sql f9f03d6c1d70231871e2e683c9318c98f55afbd0fd125a43e712d328f019d678'
  ];
  expected_fingerprints CONSTANT text[] := ARRAY[
    ARRAY['columns', '9bb8d3b1fc0244fe3b4cbc4672a76e3d'],
    ARRAY['constraints', '5fe92d321e6b4cbc0d543ce67ebf4e4a'],
    ARRAY['functions', '268227959fc6cda50e72c20b466fb7be'],
    ARRAY['indexes', '7300b59d765230f96b0db83b2e46d738'],
    ARRAY['runtime_grants', 'ebd2fa1b1c7689d306b59361f16394d8'],
    ARRAY['tables', 'c0a117b8f57473e59d1e1da99783cad2'],
    ARRAY['triggers', '3d231cd97501ca3232b0d58e6e370357'],
    ARRAY['types', 'd41d8cd98f00b204e9800998ecf8427e']
  ];
  found text[];
  pair text[];
  actual text;
  differing text[] := ARRAY[]::text[];
BEGIN
  SET LOCAL ROLE smeassistant_migrator;
  IF current_user::text <> 'smeassistant_migrator' THEN
    RAISE EXCEPTION 'reconcile-journal refused: running as %, not smeassistant_migrator', current_user;
  END IF;

  PERFORM pg_advisory_xact_lock(1936549221, 3);

  SELECT coalesce(array_agg(ordinal::text || ' ' || name || ' ' || checksum ORDER BY ordinal), ARRAY[]::text[])
    INTO found
    FROM neon_migrations.journal;
  IF found IS DISTINCT FROM expected_journal THEN
    RAISE EXCEPTION 'reconcile-journal refused: neon_migrations.journal is not exactly 0001-0008 with the expected checksums (it has % rows)', cardinality(found);
  END IF;

  FOREACH pair SLICE 1 IN ARRAY expected_fingerprints LOOP
    EXECUTE 'SELECT fingerprint FROM (' || $fp$SELECT category, md5(coalesce(body, '')) AS fingerprint FROM (
  SELECT 'tables' AS category, string_agg(c.relname || ' rls=' || c.relrowsecurity::text, E'\n' ORDER BY c.relname) AS body
    FROM pg_class c WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p', 'v', 'm')
  UNION ALL
  SELECT 'columns', string_agg(c.relname || '.' || a.attname || ' ' || format_type(a.atttypid, a.atttypmod)
      || CASE WHEN a.attnotnull THEN ' not null' ELSE '' END || coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), ''),
      E'\n' ORDER BY c.relname, a.attname)
    FROM pg_class c JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
    WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p', 'v', 'm')
  UNION ALL
  SELECT 'indexes', string_agg(indexdef, E'\n' ORDER BY indexname) FROM pg_indexes WHERE schemaname = 'public'
  UNION ALL
  SELECT 'constraints', string_agg(conrelid::regclass::text || ' ' || conname || ' ' || pg_get_constraintdef(oid), E'\n'
      ORDER BY conrelid::regclass::text COLLATE "C", conname)
    FROM pg_constraint WHERE connamespace = 'public'::regnamespace
  UNION ALL
  SELECT 'functions', string_agg(p.oid::regprocedure::text || ' ' || md5(p.prosrc) || ' secdef=' || p.prosecdef::text
      || ' cfg=' || coalesce(array_to_string(p.proconfig, ','), '') || ' runtime=' || has_function_privilege('sme_app_runtime', p.oid, 'EXECUTE')::text
      || ' public=' || (EXISTS (SELECT 1 FROM aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) x WHERE x.grantee = 0 AND x.privilege_type = 'EXECUTE'))::text,
      E'\n' ORDER BY p.oid::regprocedure::text COLLATE "C")
    FROM pg_proc p WHERE p.pronamespace = 'public'::regnamespace
  UNION ALL
  SELECT 'runtime_grants', string_agg(c.relname || ' ' || x.privilege_type, E'\n' ORDER BY c.relname, x.privilege_type COLLATE "C")
    FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) x
    WHERE c.relnamespace = 'public'::regnamespace AND x.grantee = 'sme_app_runtime'::regrole
  UNION ALL
  SELECT 'triggers', string_agg(t.tgrelid::regclass::text || ' ' || pg_get_triggerdef(t.oid), E'\n' ORDER BY t.tgrelid::regclass::text COLLATE "C", t.tgname)
    FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid WHERE c.relnamespace = 'public'::regnamespace AND NOT t.tgisinternal
  UNION ALL
  SELECT 'types', string_agg(t.typname || ' ' || t.typtype::text || ' ' || coalesce((SELECT string_agg(e.enumlabel, ',' ORDER BY e.enumsortorder) FROM pg_enum e WHERE e.enumtypid = t.oid), ''),
      E'\n' ORDER BY t.typname)
    FROM pg_type t WHERE t.typnamespace = 'public'::regnamespace AND t.typtype IN ('e', 'd', 'c')
      AND NOT EXISTS (SELECT 1 FROM pg_class c WHERE c.reltype = t.oid)
) f ORDER BY category COLLATE "C"$fp$ || ') s WHERE category = $1' INTO actual USING pair[1];
    IF actual IS DISTINCT FROM pair[2] THEN
      differing := differing || pair[1];
    END IF;
  END LOOP;
  IF cardinality(differing) > 0 THEN
    RAISE EXCEPTION 'reconcile-journal refused: the schema does not match 0015 in: %', array_to_string(differing, ', ');
  END IF;

  INSERT INTO neon_migrations.journal(ordinal, name, checksum) VALUES
    (9, '0009_scan_attempts.sql', '3c35ab9965be1d4821e885a2e43676c743e62f25435e4d59bd46d2c34a3d1768'),
    (10, '0010_mail_outbox.sql', 'ec50dceefbc20b2acbf14cf8908a550bc5c65e9feda346fd57338f1e0edce69c'),
    (11, '0011_offers.sql', '5d5a01b5796f579884de31b31aece3d54159f0b42a06042f7b228b93b0eb9449'),
    (12, '0012_work_packs.sql', 'e7933f6caac57dbc7384aae24c0fd86316cf3b521167432fe483df58cc9b7289'),
    (13, '0013_preview_events.sql', '98ec68e18a5281885ac12497af8328c3c7300ce7adfd1869f74f62912160cf24'),
    (14, '0014_publish_reply.sql', 'e2c181b78e1e2015cf624e4465b0b392b02db2ac74c157f4cb5679e0233097a3'),
    (15, '0015_action_list_indexes.sql', '61c3ce12d4342181d979e586d9077ef40664f318fa9f5051929f59c3cc3b5763');

  RAISE NOTICE 'reconcile-journal: schema matches 0015; recorded journal rows 9-15';
END
$reconcile$;
