import { describe, it, expect, vi } from "vitest";
import { readiness } from "../scripts/neon/readiness";
const env = { DATABASE_URL:'postgresql://user:credential@127.0.0.1:5432/owned_test', DATABASE_URL_UNPOOLED:'postgresql://owner:credential@127.0.0.1:5432/owned_test', NEON_AUTH_BASE_URL:'https://auth.example.test/auth', NEON_AUTH_COOKIE_SECRET:'x'.repeat(32), APP_ORIGIN:'https://app.example.test', NEXT_PUBLIC_SITE_URL:'https://app.example.test', NEON_READINESS_HOST:'127.0.0.1', NEON_READINESS_DATABASE:'owned_test' };
describe('sanitized read-only readiness',()=>{
 it.each(['DATABASE_URL','DATABASE_URL_UNPOOLED','NEON_AUTH_BASE_URL','NEON_AUTH_COOKIE_SECRET','APP_ORIGIN','NEXT_PUBLIC_SITE_URL','NEON_READINESS_HOST','NEON_READINESS_DATABASE'])('rejects missing %s before connecting', async key=>{const connect=vi.fn();expect((await readiness({...env,[key]:''},connect)).status).toBe('not_ready');expect(connect).not.toHaveBeenCalled();});
 it.each([{NEON_AUTH_BASE_URL:'postgresql://user:credential@db/auth'},{NEON_AUTH_BASE_URL:'https://user:credential@auth.example.test/auth'},{NEON_AUTH_COOKIE_SECRET:'NEON_AUTH_COOKIE_SECRET'},{NEXT_PUBLIC_SITE_URL:'https://other.example.test'},{NEON_READINESS_DATABASE:'other'},{DATABASE_URL_UNPOOLED:'postgresql://owner:credential@elsewhere/owned_test'},{DATABASE_URL_UNPOOLED:env.DATABASE_URL_UNPOOLED+'?host=elsewhere'},{DATABASE_URL_UNPOOLED:'postgresql://owner:credential@127.0.0.1:7777/owned_test'}])('rejects invalid config %j',async delta=>{const connect=vi.fn();expect((await readiness({...env,...delta},connect)).status).toBe('not_ready');expect(connect).not.toHaveBeenCalled();});
 it('sanitizes connection failures',async()=>{const result=await readiness(env,async()=>{throw new Error(env.DATABASE_URL)});expect(result.category).toBe('connection');expect(JSON.stringify(result)).not.toContain('credential');});
 it('requires the journal',async()=>{const query=vi.fn(async (sql:string)=>({rows:[sql.includes('current_database')?{database:'owned_test'}:{journal:null}]}));const close=vi.fn(async()=>{});expect((await readiness(env,async()=>({query,end:close}))).category).toBe('schema');expect(close).toHaveBeenCalled();expect(query.mock.calls.every(([q])=>!String(q).includes('INSERT'))).toBe(true);});
});
