import { writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { is } from "drizzle-orm";
import { PgTable, getTableConfig } from "drizzle-orm/pg-core";
import * as schema from "../../lib/db/schema";

/**
 * Read-only SQL that names every application-declared column missing from the
 * database it runs on (F-16, 2026-10-09). An operator pastes it into the Neon
 * SQL Editor, which needs no connection string here. `neon:readiness` checks
 * the same thing but needs credentials and reports only a category.
 *
 * Production's owner home failed for a week because the deployed database was
 * at 0008 while the journal elsewhere said 0014; this names the exact gap.
 * Regenerate with `corepack pnpm db:missing-columns-sql` whenever the schema
 * changes; tests/missing-columns-sql.test.ts fails until the file matches.
 */
export const MISSING_COLUMNS_SQL_PATH = "docs/operations/check-missing-columns.sql";

export function buildMissingColumnsSql(): string {
  // Sorted by table name: module namespace key order differs between tsx and
  // Vitest, and the committed file must be byte-stable.
  const tables = Object.values(schema)
    .filter((value) => is(value, PgTable))
    .map((value) => getTableConfig(value as PgTable))
    .sort((a, b) => a.name.localeCompare(b.name));
  const pairs = tables.flatMap((table) => table.columns.map((column) => `('${table.name}','${column.name}')`));
  return `-- Read-only. Lists all application columns that do not exist in this database.
-- Generated by scripts/neon/missing-columns-sql.ts from lib/db/schema (${pairs.length} columns); do not edit by hand.
-- Run it in the Neon SQL Editor on the branch and database that Vercel's DATABASE_URL points to.
-- 0 rows = every declared column exists. Any row names a column the application reads that is missing.
SELECT current_database() AS db,
       (SELECT max(ordinal) FROM neon_migrations.journal) AS last_migration,
       e.tbl AS missing_table, e.col AS missing_column
FROM (VALUES ${pairs.join(",")}) AS e(tbl, col)
WHERE NOT EXISTS (SELECT 1 FROM information_schema.columns c
                  WHERE c.table_schema = 'public' AND c.table_name = e.tbl AND c.column_name = e.col)
ORDER BY e.tbl, e.col;
`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  writeFileSync(MISSING_COLUMNS_SQL_PATH, buildMissingColumnsSql());
  console.log(`wrote ${MISSING_COLUMNS_SQL_PATH}`);
}
