// Complete final business catalog. SQL migrations are authoritative for functions and grants.
import { sql } from "drizzle-orm";
import { pgTable, uuid, text, timestamp, boolean, integer, smallint, bigserial, numeric, jsonb, primaryKey, unique, foreignKey, check, index, uniqueIndex, pgPolicy, type AnyPgColumn } from "drizzle-orm/pg-core";
import { appUsers } from "./identity";

export const actionMeasurements = pgTable("action_measurements", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 actionId: uuid("action_id").notNull(),
 beforeSnapshotId: uuid("before_snapshot_id"),
 afterSnapshotId: uuid("after_snapshot_id"),
 metricKey: text("metric_key").notNull(),
 beforeValue: numeric("before_value"),
 afterValue: numeric("after_value"),
 delta: numeric("delta"),
 factType: text("fact_type").notNull(),
 windowDays: integer("window_days"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"action_measurements_action_id_fkey",columns:[t.actionId],foreignColumns:[((): AnyPgColumn => actions.id)()]}).onDelete("cascade"),
 foreignKey({name:"action_measurements_after_snapshot_id_fkey",columns:[t.afterSnapshotId],foreignColumns:[((): AnyPgColumn => scanSnapshots.id)()]}).onDelete("set null"),
 foreignKey({name:"action_measurements_before_snapshot_id_fkey",columns:[t.beforeSnapshotId],foreignColumns:[((): AnyPgColumn => scanSnapshots.id)()]}).onDelete("set null"),
 check("action_measurements_fact_type_check", sql.raw("(fact_type = ANY (ARRAY['Observed'::text, 'Attributed'::text, 'Unknown'::text]))")),
 primaryKey({name:"action_measurements_pkey",columns:[t.id]}),
 foreignKey({name:"action_measurements_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const actionRuns = pgTable("action_runs", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 actionId: uuid("action_id").notNull(),
 agentKey: text("agent_key").notNull(),
 state: text("state").notNull().default(sql.raw("'queued'::text")),
 input: jsonb("input"),
 output: jsonb("output"),
 model: text("model"),
 promptVersion: text("prompt_version"),
 error: text("error"),
 inputTokens: integer("input_tokens"),
 outputTokens: integer("output_tokens"),
 costUsd: numeric("cost_usd"),
 requestedBy: uuid("requested_by"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 startedAt: timestamp("started_at", {withTimezone:true, mode:"string"}),
 finishedAt: timestamp("finished_at", {withTimezone:true, mode:"string"}),
}, t => [
 foreignKey({name:"action_runs_action_id_fkey",columns:[t.actionId],foreignColumns:[((): AnyPgColumn => actions.id)()]}).onDelete("cascade"),
 primaryKey({name:"action_runs_pkey",columns:[t.id]}),
 foreignKey({name:"action_runs_requested_by_fkey",columns:[t.requestedBy],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("set null"),
 check("action_runs_state_check", sql.raw("(state = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text, 'timed_out'::text]))")),
 foreignKey({name:"action_runs_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const actions = pgTable("actions", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 locationId: uuid("location_id"),
 templateKey: text("template_key").notNull(),
 source: text("source").notNull().default(sql.raw("'finding'::text")),
 sourceFindingKeys: text("source_finding_keys").array().notNull().default(sql.raw("'{}'::text[]")),
 sourceSnapshotId: uuid("source_snapshot_id"),
 title: jsonb("title").notNull(),
 summary: jsonb("summary").notNull(),
 evidence: jsonb("evidence").notNull(),
 priority: text("priority").notNull(),
 priorityScore: numeric("priority_score").notNull(),
 priorityFactors: jsonb("priority_factors").notNull(),
 effortMinutes: integer("effort_minutes").notNull(),
 requiredInputs: jsonb("required_inputs").notNull().default(sql.raw("'[]'::jsonb")),
 providedInputs: jsonb("provided_inputs").notNull().default(sql.raw("'{}'::jsonb")),
 assigneeUserId: uuid("assignee_user_id"),
 dueAt: timestamp("due_at", {withTimezone:true, mode:"string"}),
 actionState: text("action_state").notNull().default(sql.raw("'recommended'::text")),
 measurementState: text("measurement_state").notNull().default(sql.raw("'not_eligible'::text")),
 capability: text("capability").notNull(),
 dedupeKey: text("dedupe_key").notNull(),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 updatedAt: timestamp("updated_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 completedAt: timestamp("completed_at", {withTimezone:true, mode:"string"}),
}, t => [
 check("actions_action_state_check", sql.raw("(action_state = ANY (ARRAY['recommended'::text, 'needs_input'::text, 'ready'::text, 'in_progress'::text, 'completed'::text, 'dismissed'::text, 'cancelled'::text, 'expired'::text]))")),
 foreignKey({name:"actions_assignee_user_id_fkey",columns:[t.assigneeUserId],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("set null"),
 check("actions_capability_check", sql.raw("(capability = ANY (ARRAY['Live'::text, 'Beta'::text, 'Demo'::text, 'Requires connection'::text, 'Planned'::text]))")),
 foreignKey({name:"actions_location_id_fkey",columns:[t.locationId],foreignColumns:[((): AnyPgColumn => locations.id)()]}).onDelete("set null"),
 check("actions_measurement_state_check", sql.raw("(measurement_state = ANY (ARRAY['not_eligible'::text, 'awaiting_comparable_scan'::text, 'measured'::text, 'insufficient_coverage'::text]))")),
 primaryKey({name:"actions_pkey",columns:[t.id]}),
 check("actions_priority_check", sql.raw("(priority = ANY (ARRAY['urgent'::text, 'high'::text, 'medium'::text, 'low'::text]))")),
 check("actions_source_check", sql.raw("(source = ANY (ARRAY['finding'::text, 'owner_objective'::text, 'system'::text]))")),
 foreignKey({name:"actions_source_snapshot_id_fkey",columns:[t.sourceSnapshotId],foreignColumns:[((): AnyPgColumn => scanSnapshots.id)()]}).onDelete("set null"),
 foreignKey({name:"actions_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 uniqueIndex("actions_open_dedupe_idx").using("btree", sql.raw("dedupe_key")).where(sql.raw("(action_state <> ALL (ARRAY['completed'::text, 'dismissed'::text, 'cancelled'::text, 'expired'::text]))")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const aeoSurfaceSnapshots = pgTable("aeo_surface_snapshots", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id").notNull(),
 placeId: text("place_id").notNull(),
 surface: text("surface").notNull(),
 queryText: text("query_text").notNull(),
 locale: text("locale").notNull(),
 market: text("market").notNull(),
 cited: boolean("cited").notNull(),
 rank: integer("rank"),
 competitors: jsonb("competitors").notNull().default(sql.raw("'[]'::jsonb")),
 excerpt: text("excerpt"),
 capturedAt: timestamp("captured_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"aeo_surface_snapshots_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 unique("aeo_surface_snapshots_job_id_surface_query_text_key").on(t.jobId,t.surface,t.queryText),
 primaryKey({name:"aeo_surface_snapshots_pkey",columns:[t.id]}),
 check("aeo_surface_snapshots_surface_check", sql.raw("(surface = ANY (ARRAY['ai_overview'::text, 'ai_mode'::text, 'organic'::text]))")),
 index("aeo_surface_snapshots_job_idx").using("btree", sql.raw("job_id")),
 index("aeo_surface_snapshots_place_surface_idx").using("btree", sql.raw("place_id, surface, captured_at DESC")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const agentRuns = pgTable("agent_runs", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id").notNull(),
 findingKey: text("finding_key").notNull(),
 agentKey: text("agent_key").notNull(),
 status: text("status").notNull().default(sql.raw("'draft'::text")),
 output: jsonb("output").notNull(),
 inputTokens: integer("input_tokens"),
 outputTokens: integer("output_tokens"),
 costUsd: numeric("cost_usd"),
 reviewedBy: uuid("reviewed_by"),
 reviewedAt: timestamp("reviewed_at", {withTimezone:true, mode:"string"}),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 check("agent_runs_agent_key_check", sql.raw("(agent_key = ANY (ARRAY['review_reply_agent'::text, 'gbp_post_agent'::text]))")),
 foreignKey({name:"agent_runs_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 primaryKey({name:"agent_runs_pkey",columns:[t.id]}),
 foreignKey({name:"agent_runs_reviewed_by_fkey",columns:[t.reviewedBy],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}),
 check("agent_runs_status_check", sql.raw("(status = ANY (ARRAY['draft'::text, 'approved'::text, 'rejected'::text]))")),
 index("agent_runs_job_status_idx").using("btree", sql.raw("job_id, status")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const assets = pgTable("assets", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 locationId: uuid("location_id"),
 kind: text("kind").notNull(),
 storagePath: text("storage_path").notNull(),
 filename: text("filename").notNull(),
 altText: text("alt_text"),
 rightsStatus: text("rights_status").notNull().default(sql.raw("'needs_review'::text")),
 rightsConfirmedAt: timestamp("rights_confirmed_at", {withTimezone:true, mode:"string"}),
 uploadedBy: uuid("uploaded_by"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 check("assets_kind_check", sql.raw("(kind = ANY (ARRAY['image'::text, 'document'::text, 'menu'::text]))")),
 foreignKey({name:"assets_location_id_fkey",columns:[t.locationId],foreignColumns:[((): AnyPgColumn => locations.id)()]}).onDelete("set null"),
 primaryKey({name:"assets_pkey",columns:[t.id]}),
 check("assets_rights_status_check", sql.raw("(rights_status = ANY (ARRAY['approved'::text, 'needs_review'::text, 'rejected'::text]))")),
 foreignKey({name:"assets_uploaded_by_fkey",columns:[t.uploadedBy],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("set null"),
 foreignKey({name:"assets_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const auditEvents = pgTable("audit_events", {
 id: bigserial("id", {mode:"bigint"}).notNull(),
 workspaceId: uuid("workspace_id"),
 locationId: uuid("location_id"),
 actorType: text("actor_type").notNull(),
 actorId: uuid("actor_id"),
 event: text("event").notNull(),
 entityType: text("entity_type"),
 entityId: uuid("entity_id"),
 payload: jsonb("payload"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 idempotencyKey: text("idempotency_key"),
}, t => [
 check("audit_events_actor_type_check", sql.raw("(actor_type = ANY (ARRAY['user'::text, 'agent'::text, 'system'::text, 'scanner'::text]))")),
 primaryKey({name:"audit_events_pkey",columns:[t.id]}),
 foreignKey({name:"audit_events_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 uniqueIndex("audit_events_idempotency_key_idx").using("btree", sql.raw("idempotency_key")),
 index("audit_events_workspace_idx").using("btree", sql.raw("workspace_id, created_at DESC")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const auditFindings = pgTable("audit_findings", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id"),
 workspaceId: uuid("workspace_id"),
 findingKey: text("finding_key").notNull(),
 module: text("module").notNull(),
 severity: text("severity").notNull(),
 scoreImpact: numeric("score_impact"),
 ownerMessageZh: text("owner_message_zh"),
 evidence: jsonb("evidence"),
 v02AgentHint: text("v02_agent_hint"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).default(sql.raw("now()")),
 ownerMessageEn: text("owner_message_en"),
 ownerMessageTw: text("owner_message_tw"),
 ownerActionZh: text("owner_action_zh"),
 ownerActionEn: text("owner_action_en"),
}, t => [
 foreignKey({name:"audit_findings_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 primaryKey({name:"audit_findings_pkey",columns:[t.id]}),
 uniqueIndex("audit_findings_job_finding_key_unique_idx").using("btree", sql.raw("job_id, finding_key")),
 index("audit_findings_job_id_finding_key_idx").using("btree", sql.raw("job_id, finding_key")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const auditJobs = pgTable("audit_jobs", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id"),
 businessName: text("business_name").notNull(),
 igHandle: text("ig_handle"),
 websiteUrl: text("website_url"),
 industry: text("industry"),
 district: text("district"),
 userRole: text("user_role"),
 status: text("status").notNull().default(sql.raw("'queued'::text")),
 rawPayload: jsonb("raw_payload"),
 overallScore: numeric("overall_score"),
 moduleScores: jsonb("module_scores"),
 shareSlug: text("share_slug"),
 unlocked: boolean("unlocked").default(sql.raw("false")),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).default(sql.raw("now()")),
 completedAt: timestamp("completed_at", {withTimezone:true, mode:"string"}),
 rawData: jsonb("raw_data"),
 summaryEn: text("summary_en"),
 summaryZh: text("summary_zh"),
 summaryTw: text("summary_tw"),
 region: text("region").notNull().default(sql.raw("'hk'::text")),
 processingStage: text("processing_stage"),
 moduleResults: jsonb("module_results"),
 scoreCoverage: numeric("score_coverage"),
 scoringVersion: text("scoring_version"),
 inputSnapshot: jsonb("input_snapshot"),
 failureCategory: text("failure_category"),
 failureCorrelationId: uuid("failure_correlation_id"),
 attemptCount: integer("attempt_count").notNull().default(sql.raw("0")),
 lastAttemptAt: timestamp("last_attempt_at", {withTimezone:true, mode:"string"}),
 businessObjective: text("business_objective"),
 placeId: text("place_id"),
 placeMatchConfidence: text("place_match_confidence"),
 parentJobId: uuid("parent_job_id"),
 locationId: uuid("location_id"),
}, t => [
 foreignKey({name:"audit_jobs_location_id_fkey",columns:[t.locationId],foreignColumns:[((): AnyPgColumn => locations.id)()]}).onDelete("set null"),
 foreignKey({name:"audit_jobs_parent_job_id_fkey",columns:[t.parentJobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 primaryKey({name:"audit_jobs_pkey",columns:[t.id]}),
 unique("audit_jobs_share_slug_key").on(t.shareSlug),
 check("audit_jobs_status_check", sql.raw("(status = ANY (ARRAY['queued'::text, 'collecting'::text, 'scoring'::text, 'persisting'::text, 'done'::text, 'partial'::text, 'failed'::text]))")),
 foreignKey({name:"audit_jobs_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("set null"),
 index("audit_jobs_place_created_idx").using("btree", sql.raw("place_id, created_at DESC")),
 index("audit_jobs_share_slug_idx").using("btree", sql.raw("share_slug")),
 index("audit_jobs_stale_claim_idx").using("btree", sql.raw("last_attempt_at")).where(sql.raw("(status = ANY (ARRAY['collecting'::text, 'scoring'::text, 'persisting'::text]))")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const brandProfiles = pgTable("brand_profiles", {
 workspaceId: uuid("workspace_id").notNull(),
 voice: text("voice").notNull().default(sql.raw("'warm'::text")),
 approvedClaims: text("approved_claims").array().notNull().default(sql.raw("'{}'::text[]")),
 prohibitedTerms: text("prohibited_terms").array().notNull().default(sql.raw("'{}'::text[]")),
 languages: text("languages").array().notNull().default(sql.raw("'{zh-HK}'::text[]")),
 facts: jsonb("facts").notNull().default(sql.raw("'{}'::jsonb")),
 updatedAt: timestamp("updated_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 primaryKey({name:"brand_profiles_pkey",columns:[t.workspaceId]}),
 foreignKey({name:"brand_profiles_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const consentRecords = pgTable("consent_records", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id").notNull(),
 leadId: uuid("lead_id"),
 consentType: text("consent_type").notNull(),
 granted: boolean("granted").notNull(),
 policyVersion: text("policy_version").notNull(),
 locale: text("locale").notNull(),
 recordedAt: timestamp("recorded_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"consent_records_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 foreignKey({name:"consent_records_lead_id_fkey",columns:[t.leadId],foreignColumns:[((): AnyPgColumn => leads.id)()]}).onDelete("set null"),
 primaryKey({name:"consent_records_pkey",columns:[t.id]}),
 index("consent_records_job_id_idx").using("btree", sql.raw("job_id")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const deliveries = pgTable("deliveries", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 versionId: uuid("version_id").notNull(),
 mode: text("mode").notNull(),
 channel: text("channel"),
 state: text("state").notNull(),
 counted: boolean("counted").notNull().default(sql.raw("false")),
 idempotencyKey: text("idempotency_key").notNull(),
 payload: jsonb("payload"),
 createdBy: uuid("created_by"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"deliveries_created_by_fkey",columns:[t.createdBy],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("set null"),
 unique("deliveries_idempotency_key_key").on(t.idempotencyKey),
 check("deliveries_mode_check", sql.raw("(mode = ANY (ARRAY['export'::text, 'copy'::text, 'publish'::text]))")),
 primaryKey({name:"deliveries_pkey",columns:[t.id]}),
 check("deliveries_state_check", sql.raw("(state = ANY (ARRAY['export_ready'::text, 'exported'::text, 'scheduled'::text, 'publishing'::text, 'published'::text, 'failed'::text, 'cancelled'::text]))")),
 foreignKey({name:"deliveries_version_id_fkey",columns:[t.versionId],foreignColumns:[((): AnyPgColumn => outputVersions.id)()]}).onDelete("cascade"),
 foreignKey({name:"deliveries_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const erasureEvents = pgTable("erasure_events", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 erasedJobId: uuid("erased_job_id").notNull(),
 staffUserId: uuid("staff_user_id").notNull(),
 staffEmailNormalized: text("staff_email_normalized").notNull(),
 reason: text("reason").notNull(),
 removedCounts: jsonb("removed_counts").notNull(),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 primaryKey({name:"erasure_events_pkey",columns:[t.id]}),
 index("erasure_events_created_at_idx").using("btree", sql.raw("created_at DESC")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const leads = pgTable("leads", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id"),
 workspaceId: uuid("workspace_id"),
 whatsapp: text("whatsapp"),
 email: text("email"),
 consentBdContact: boolean("consent_bd_contact"),
 leadScore: integer("lead_score"),
 routedTo: text("routed_to"),
 routedAt: timestamp("routed_at", {withTimezone:true, mode:"string"}),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).default(sql.raw("now()")),
 preferredContactChannel: text("preferred_contact_channel"),
 contactIdentifier: text("contact_identifier"),
 businessObjective: text("business_objective"),
}, t => [
 foreignKey({name:"leads_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 primaryKey({name:"leads_pkey",columns:[t.id]}),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const locations = pgTable("locations", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 slug: text("slug").notNull(),
 name: text("name").notNull(),
 address: text("address"),
 district: text("district"),
 placeId: text("place_id"),
 igHandle: text("ig_handle"),
 websiteUrl: text("website_url"),
 isPrimary: boolean("is_primary").notNull().default(sql.raw("false")),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 primaryKey({name:"locations_pkey",columns:[t.id]}),
 foreignKey({name:"locations_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 unique("locations_workspace_id_slug_key").on(t.workspaceId,t.slug),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const notificationEvents = pgTable("notification_events", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 jobId: uuid("job_id"),
 sectionsIncluded: text("sections_included").array().notNull(),
 resendMessageId: text("resend_message_id"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"notification_events_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("set null"),
 primaryKey({name:"notification_events_pkey",columns:[t.id]}),
 foreignKey({name:"notification_events_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 uniqueIndex("notification_events_job_id_key").using("btree", sql.raw("job_id")).where(sql.raw("(job_id IS NOT NULL)")),
 index("notification_events_workspace_idx").using("btree", sql.raw("workspace_id, created_at DESC")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const oauthConnections = pgTable("oauth_connections", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 provider: text("provider").notNull(),
 accountRef: text("account_ref"),
 accessTokenEncrypted: text("access_token_encrypted").notNull(),
 refreshTokenEncrypted: text("refresh_token_encrypted"),
 scopes: text("scopes").array().notNull().default(sql.raw("'{}'::text[]")),
 expiresAt: timestamp("expires_at", {withTimezone:true, mode:"string"}),
 status: text("status").notNull().default(sql.raw("'active'::text")),
 connectedAt: timestamp("connected_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 updatedAt: timestamp("updated_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 primaryKey({name:"oauth_connections_pkey",columns:[t.id]}),
 check("oauth_connections_provider_check", sql.raw("(provider = ANY (ARRAY['instagram'::text, 'google_gbp'::text, 'ga4'::text]))")),
 check("oauth_connections_status_check", sql.raw("(status = ANY (ARRAY['active'::text, 'expired'::text, 'revoked'::text, 'error'::text]))")),
 foreignKey({name:"oauth_connections_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 uniqueIndex("oauth_connections_active_provider_key").using("btree", sql.raw("workspace_id, provider")).where(sql.raw("(status = 'active'::text)")),
 index("oauth_connections_workspace_idx").using("btree", sql.raw("workspace_id")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const outputVersions = pgTable("output_versions", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 actionId: uuid("action_id").notNull(),
 versionNo: integer("version_no").notNull(),
 body: text("body").notNull(),
 altText: text("alt_text"),
 meta: jsonb("meta").notNull().default(sql.raw("'{}'::jsonb")),
 authorType: text("author_type").notNull(),
 authorUserId: uuid("author_user_id"),
 actionRunId: uuid("action_run_id"),
 approvalState: text("approval_state").notNull().default(sql.raw("'draft'::text")),
 approvedBy: uuid("approved_by"),
 approvedAt: timestamp("approved_at", {withTimezone:true, mode:"string"}),
 reviewerComment: text("reviewer_comment"),
 deliveryState: text("delivery_state").notNull().default(sql.raw("'not_requested'::text")),
 firstExportedAt: timestamp("first_exported_at", {withTimezone:true, mode:"string"}),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"output_versions_action_id_fkey",columns:[t.actionId],foreignColumns:[((): AnyPgColumn => actions.id)()]}).onDelete("cascade"),
 unique("output_versions_action_id_version_no_key").on(t.actionId,t.versionNo),
 foreignKey({name:"output_versions_action_run_id_fkey",columns:[t.actionRunId],foreignColumns:[((): AnyPgColumn => actionRuns.id)()]}).onDelete("set null"),
 check("output_versions_approval_state_check", sql.raw("(approval_state = ANY (ARRAY['draft'::text, 'changes_requested'::text, 'approved'::text, 'rejected'::text, 'superseded'::text]))")),
 foreignKey({name:"output_versions_approved_by_fkey",columns:[t.approvedBy],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("set null"),
 check("output_versions_author_type_check", sql.raw("(author_type = ANY (ARRAY['user'::text, 'agent'::text]))")),
 foreignKey({name:"output_versions_author_user_id_fkey",columns:[t.authorUserId],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("set null"),
 check("output_versions_delivery_state_check", sql.raw("(delivery_state = ANY (ARRAY['not_requested'::text, 'export_ready'::text, 'exported'::text, 'scheduled'::text, 'publishing'::text, 'published'::text, 'failed'::text, 'cancelled'::text]))")),
 primaryKey({name:"output_versions_pkey",columns:[t.id]}),
 foreignKey({name:"output_versions_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const rateLimitBuckets = pgTable("rate_limit_buckets", {
 bucketKey: text("bucket_key").notNull(),
 windowStartedAt: timestamp("window_started_at", {withTimezone:true, mode:"string"}).notNull(),
 requestCount: integer("request_count").notNull().default(sql.raw("0")),
 updatedAt: timestamp("updated_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 expiresAt: timestamp("expires_at", {withTimezone:true, mode:"string"}).notNull(),
}, t => [
 primaryKey({name:"rate_limit_buckets_pkey",columns:[t.bucketKey]}),
 check("rate_limit_buckets_request_count_check", sql.raw("(request_count >= 0)")),
 index("rate_limit_buckets_expires_at_idx").using("btree", sql.raw("expires_at")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const reportAccessGrants = pgTable("report_access_grants", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id").notNull(),
 leadId: uuid("lead_id"),
 tokenHash: text("token_hash").notNull(),
 idempotencyKey: text("idempotency_key").notNull(),
 purpose: text("purpose").notNull(),
 emailNormalized: text("email_normalized"),
 expiresAt: timestamp("expires_at", {withTimezone:true, mode:"string"}).notNull(),
 redeemedAt: timestamp("redeemed_at", {withTimezone:true, mode:"string"}),
 revokedAt: timestamp("revoked_at", {withTimezone:true, mode:"string"}),
 lastUsedAt: timestamp("last_used_at", {withTimezone:true, mode:"string"}),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 check("report_access_grants_idempotency_key_check", sql.raw("(btrim(idempotency_key) <> ''::text)")),
 foreignKey({name:"report_access_grants_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 foreignKey({name:"report_access_grants_lead_id_fkey",columns:[t.leadId],foreignColumns:[((): AnyPgColumn => leads.id)()]}).onDelete("set null"),
 primaryKey({name:"report_access_grants_pkey",columns:[t.id]}),
 check("report_access_grants_token_hash_sha256_check", sql.raw("(token_hash ~ '^[0-9a-f]{64}$'::text)")),
 index("report_access_grants_job_id_idx").using("btree", sql.raw("job_id")),
 uniqueIndex("report_access_grants_job_idempotency_key_unique_idx").using("btree", sql.raw("job_id, idempotency_key")),
 uniqueIndex("report_access_grants_token_hash_unique_idx").using("btree", sql.raw("token_hash")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const reportEvidence = pgTable("report_evidence", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id").notNull(),
 provider: text("provider").notNull(),
 evidenceType: text("evidence_type").notNull(),
 sourceId: text("source_id").notNull(),
 sourceUrl: text("source_url"),
 capturedAt: timestamp("captured_at", {withTimezone:true, mode:"string"}).notNull(),
 publishedAt: timestamp("published_at", {withTimezone:true, mode:"string"}),
 textContent: text("text_content"),
 metadata: jsonb("metadata").notNull().default(sql.raw("'{}'::jsonb")),
 storageBucket: text("storage_bucket"),
 storagePath: text("storage_path"),
 contentSha256: text("content_sha256"),
 mimeType: text("mime_type"),
 byteSize: integer("byte_size"),
 width: integer("width"),
 height: integer("height"),
 collectionStatus: text("collection_status").notNull(),
 limitationCode: text("limitation_code"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 check("report_evidence_byte_size_check", sql.raw("((byte_size IS NULL) OR ((byte_size >= 1) AND (byte_size <= 5242880)))")),
 check("report_evidence_collection_status_check", sql.raw("(collection_status = ANY (ARRAY['stored'::text, 'metadata_only'::text, 'failed'::text]))")),
 check("report_evidence_content_sha256_check", sql.raw("((content_sha256 IS NULL) OR (content_sha256 ~ '^[0-9a-f]{64}$'::text))")),
 check("report_evidence_evidence_type_check", sql.raw("(evidence_type = ANY (ARRAY['profile'::text, 'post'::text, 'reel'::text, 'story'::text, 'highlight'::text, 'photo'::text, 'review'::text]))")),
 check("report_evidence_height_check", sql.raw("((height IS NULL) OR ((height >= 1) AND (height <= 4800)))")),
 foreignKey({name:"report_evidence_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 unique("report_evidence_job_id_provider_evidence_type_source_id_key").on(t.jobId,t.provider,t.evidenceType,t.sourceId),
 primaryKey({name:"report_evidence_pkey",columns:[t.id]}),
 check("report_evidence_provider_check", sql.raw("(provider = ANY (ARRAY['instagram'::text, 'google_maps'::text]))")),
 check("report_evidence_width_check", sql.raw("((width IS NULL) OR ((width >= 1) AND (width <= 4800)))")),
 index("report_evidence_job_captured_idx").using("btree", sql.raw("job_id, captured_at DESC")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const scanDiffs = pgTable("scan_diffs", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 baseJobId: uuid("base_job_id").notNull(),
 headJobId: uuid("head_job_id").notNull(),
 comparable: boolean("comparable").notNull(),
 incomparableReason: text("incomparable_reason"),
 compositeWithheldReason: text("composite_withheld_reason"),
 intersectionModules: text("intersection_modules").array().notNull().default(sql.raw("'{}'::text[]")),
 compositeBase: numeric("composite_base"),
 compositeHead: numeric("composite_head"),
 compositeDelta: numeric("composite_delta"),
 resolvedFindings: text("resolved_findings").array().notNull().default(sql.raw("'{}'::text[]")),
 regressedFindings: text("regressed_findings").array().notNull().default(sql.raw("'{}'::text[]")),
 decayedFindings: text("decayed_findings").array().notNull().default(sql.raw("'{}'::text[]")),
 lostCoverage: text("lost_coverage").array().notNull().default(sql.raw("'{}'::text[]")),
 gainedCoverage: text("gained_coverage").array().notNull().default(sql.raw("'{}'::text[]")),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"scan_diffs_base_job_id_fkey",columns:[t.baseJobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 unique("scan_diffs_base_job_id_head_job_id_key").on(t.baseJobId,t.headJobId),
 foreignKey({name:"scan_diffs_head_job_id_fkey",columns:[t.headJobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 primaryKey({name:"scan_diffs_pkey",columns:[t.id]}),
 index("scan_diffs_head_idx").using("btree", sql.raw("head_job_id")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const scanEvents = pgTable("scan_events", {
 id: bigserial("id", {mode:"bigint"}).notNull(),
 jobId: uuid("job_id"),
 eventName: text("event_name"),
 payload: jsonb("payload"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).default(sql.raw("now()")),
 anonymousSessionId: text("anonymous_session_id"),
 properties: jsonb("properties"),
 dedupeKey: text("dedupe_key"),
}, t => [
 foreignKey({name:"scan_events_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 primaryKey({name:"scan_events_pkey",columns:[t.id]}),
 uniqueIndex("scan_events_dedupe_identity_unique_idx").using("btree", sql.raw("job_id, anonymous_session_id, event_name, dedupe_key")),
 index("scan_events_job_id_created_at_idx").using("btree", sql.raw("job_id, created_at DESC")),
 index("scan_events_job_id_event_name_idx").using("btree", sql.raw("job_id, event_name")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const scanSchedules = pgTable("scan_schedules", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 placeId: text("place_id").notNull(),
 inputSnapshot: jsonb("input_snapshot").notNull(),
 cadence: text("cadence").notNull().default(sql.raw("'monthly'::text")),
 anniversaryDay: smallint("anniversary_day").notNull(),
 lastJobId: uuid("last_job_id"),
 nextRunAt: timestamp("next_run_at", {withTimezone:true, mode:"string"}).notNull(),
 createdBy: uuid("created_by").notNull(),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 workspaceId: uuid("workspace_id"),
}, t => [
 check("scan_schedules_anniversary_day_check", sql.raw("((anniversary_day >= 1) AND (anniversary_day <= 28))")),
 check("scan_schedules_cadence_check", sql.raw("(cadence = ANY (ARRAY['monthly'::text, 'paused'::text]))")),
 foreignKey({name:"scan_schedules_created_by_fkey",columns:[t.createdBy],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("restrict"),
 foreignKey({name:"scan_schedules_last_job_id_fkey",columns:[t.lastJobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("set null"),
 primaryKey({name:"scan_schedules_pkey",columns:[t.id]}),
 unique("scan_schedules_place_id_key").on(t.placeId),
 foreignKey({name:"scan_schedules_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("set null"),
 index("scan_schedules_due_idx").using("btree", sql.raw("next_run_at")).where(sql.raw("(cadence = 'monthly'::text)")),
 index("scan_schedules_workspace_idx").using("btree", sql.raw("workspace_id")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const scanSnapshots = pgTable("scan_snapshots", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id").notNull(),
 workspaceId: uuid("workspace_id"),
 locationId: uuid("location_id"),
 market: text("market").notNull(),
 observedAt: timestamp("observed_at", {withTimezone:true, mode:"string"}).notNull(),
 scoringVersion: text("scoring_version"),
 overallScore: numeric("overall_score"),
 coverage: numeric("coverage").notNull(),
 moduleStates: jsonb("module_states").notNull(),
 metrics: jsonb("metrics").notNull(),
 websiteChecks: jsonb("website_checks"),
 comparableTo: uuid("comparable_to"),
 diffId: uuid("diff_id"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"scan_snapshots_comparable_to_fkey",columns:[t.comparableTo],foreignColumns:[((): AnyPgColumn => scanSnapshots.id)()]}).onDelete("set null"),
 foreignKey({name:"scan_snapshots_diff_id_fkey",columns:[t.diffId],foreignColumns:[((): AnyPgColumn => scanDiffs.id)()]}).onDelete("set null"),
 foreignKey({name:"scan_snapshots_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 unique("scan_snapshots_job_id_key").on(t.jobId),
 foreignKey({name:"scan_snapshots_location_id_fkey",columns:[t.locationId],foreignColumns:[((): AnyPgColumn => locations.id)()]}).onDelete("set null"),
 primaryKey({name:"scan_snapshots_pkey",columns:[t.id]}),
 foreignKey({name:"scan_snapshots_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const staffReportEvents = pgTable("staff_report_events", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 staffUserId: uuid("staff_user_id").notNull(),
 staffEmailNormalized: text("staff_email_normalized").notNull(),
 jobId: uuid("job_id"),
 action: text("action").notNull(),
 metadata: jsonb("metadata"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"staff_report_events_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("set null"),
 primaryKey({name:"staff_report_events_pkey",columns:[t.id]}),
 index("staff_report_events_job_id_created_at_idx").using("btree", sql.raw("job_id, created_at DESC")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const workspaceAccessRequests = pgTable("workspace_access_requests", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id").notNull(),
 userId: uuid("user_id").notNull(),
 requestedAt: timestamp("requested_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 resolvedAt: timestamp("resolved_at", {withTimezone:true, mode:"string"}),
 resolvedByStaffUserId: uuid("resolved_by_staff_user_id"),
}, t => [
 foreignKey({name:"workspace_access_requests_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 primaryKey({name:"workspace_access_requests_pkey",columns:[t.id]}),
 foreignKey({name:"workspace_access_requests_resolved_by_staff_user_id_fkey",columns:[t.resolvedByStaffUserId],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("set null"),
 foreignKey({name:"workspace_access_requests_user_id_fkey",columns:[t.userId],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("cascade"),
 uniqueIndex("workspace_access_requests_open_idx").using("btree", sql.raw("job_id, user_id")).where(sql.raw("(resolved_at IS NULL)")),
 index("workspace_access_requests_pending_idx").using("btree", sql.raw("requested_at DESC")).where(sql.raw("(resolved_at IS NULL)")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const workspaceClaimEvents = pgTable("workspace_claim_events", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 jobId: uuid("job_id"),
 erasedJobId: text("erased_job_id"),
 workspaceId: uuid("workspace_id"),
 erasedWorkspaceId: text("erased_workspace_id"),
 matchedLocationId: text("matched_location_id").notNull(),
 claimedByUserId: uuid("claimed_by_user_id").notNull(),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"workspace_claim_events_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("set null"),
 check("workspace_claim_events_matched_location_id_check", sql.raw("(matched_location_id ~~ 'locations/%'::text)")),
 primaryKey({name:"workspace_claim_events_pkey",columns:[t.id]}),
 foreignKey({name:"workspace_claim_events_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("set null"),
 index("workspace_claim_events_claimed_by_idx").using("btree", sql.raw("claimed_by_user_id")),
 index("workspace_claim_events_job_idx").using("btree", sql.raw("job_id, created_at DESC")),
 index("workspace_claim_events_workspace_idx").using("btree", sql.raw("workspace_id, created_at DESC")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const workspaceMembers = pgTable("workspace_members", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 userId: uuid("user_id"),
 email: text("email").notNull(),
 role: text("role").notNull(),
 invitedBy: uuid("invited_by"),
 invitedAt: timestamp("invited_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 acceptedAt: timestamp("accepted_at", {withTimezone:true, mode:"string"}),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 locationScope: uuid("location_scope").array(),
}, t => [
 foreignKey({name:"workspace_members_invited_by_fkey",columns:[t.invitedBy],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("set null"),
 primaryKey({name:"workspace_members_pkey",columns:[t.id]}),
 check("workspace_members_role_check", sql.raw("(role = ANY (ARRAY['owner'::text, 'manager'::text, 'viewer'::text]))")),
 foreignKey({name:"workspace_members_user_id_fkey",columns:[t.userId],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("cascade"),
 foreignKey({name:"workspace_members_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 index("workspace_members_email_idx").using("btree", sql.raw("lower(email)")),
 uniqueIndex("workspace_members_email_idx_unique").using("btree", sql.raw("workspace_id, lower(email)")),
 uniqueIndex("workspace_members_one_owner_idx").using("btree", sql.raw("workspace_id")).where(sql.raw("(role = 'owner'::text)")),
 uniqueIndex("workspace_members_user_workspace_idx").using("btree", sql.raw("workspace_id, user_id")).where(sql.raw("(user_id IS NOT NULL)")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const workspaceNotifications = pgTable("workspace_notifications", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 userId: uuid("user_id"),
 kind: text("kind").notNull(),
 title: jsonb("title").notNull(),
 body: jsonb("body"),
 href: text("href"),
 readAt: timestamp("read_at", {withTimezone:true, mode:"string"}),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 primaryKey({name:"workspace_notifications_pkey",columns:[t.id]}),
 foreignKey({name:"workspace_notifications_user_id_fkey",columns:[t.userId],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}).onDelete("cascade"),
 foreignKey({name:"workspace_notifications_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const workspaceScanCompletions = pgTable("workspace_scan_completions", {
 jobId: uuid("job_id").notNull(),
 workspaceId: uuid("workspace_id").notNull(),
 state: text("state").notNull(),
 attempts: integer("attempts").notNull().default(sql.raw("0")),
 leaseToken: uuid("lease_token"),
 leaseUntil: timestamp("lease_until", {withTimezone:true, mode:"string"}),
 nextAttemptAt: timestamp("next_attempt_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 lastError: text("last_error"),
 completedAt: timestamp("completed_at", {withTimezone:true, mode:"string"}),
 updatedAt: timestamp("updated_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 foreignKey({name:"workspace_scan_completions_job_id_fkey",columns:[t.jobId],foreignColumns:[((): AnyPgColumn => auditJobs.id)()]}).onDelete("cascade"),
 primaryKey({name:"workspace_scan_completions_pkey",columns:[t.jobId]}),
 check("workspace_scan_completions_state_check", sql.raw("(state = ANY (ARRAY['running'::text, 'retry'::text, 'completed'::text]))")),
 foreignKey({name:"workspace_scan_completions_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const workspaceTierEvents = pgTable("workspace_tier_events", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 workspaceId: uuid("workspace_id").notNull(),
 tier: text("tier").notNull(),
 source: text("source").notNull(),
 staffUserId: uuid("staff_user_id"),
 stripeEventId: text("stripe_event_id"),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
}, t => [
 primaryKey({name:"workspace_tier_events_pkey",columns:[t.id]}),
 check("workspace_tier_events_source_check", sql.raw("(source = ANY (ARRAY['stripe_webhook'::text, 'staff_grant'::text]))")),
 foreignKey({name:"workspace_tier_events_staff_user_id_fkey",columns:[t.staffUserId],foreignColumns:[((): AnyPgColumn => appUsers.id)()]}),
 check("workspace_tier_events_tier_check", sql.raw("(tier = ANY (ARRAY['lite'::text, 'paid'::text]))")),
 foreignKey({name:"workspace_tier_events_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 uniqueIndex("workspace_tier_events_stripe_event_id_key").using("btree", sql.raw("stripe_event_id")).where(sql.raw("(stripe_event_id IS NOT NULL)")),
 index("workspace_tier_events_workspace_idx").using("btree", sql.raw("workspace_id, created_at DESC")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const workspaceUsage = pgTable("workspace_usage", {
 workspaceId: uuid("workspace_id").notNull(),
 period: text("period").notNull(),
 approvedDeliveries: integer("approved_deliveries").notNull().default(sql.raw("0")),
 allowance: integer("allowance"),
}, t => [
 primaryKey({name:"workspace_usage_pkey",columns:[t.workspaceId,t.period]}),
 foreignKey({name:"workspace_usage_workspace_id_fkey",columns:[t.workspaceId],foreignColumns:[((): AnyPgColumn => workspaces.id)()]}).onDelete("cascade"),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();

export const workspaces = pgTable("workspaces", {
 id: uuid("id").notNull().default(sql.raw("gen_random_uuid()")),
 businessName: text("business_name"),
 industry: text("industry"),
 district: text("district"),
 market: text("market"),
 tier: text("tier").notNull().default(sql.raw("'lite'::text")),
 createdAt: timestamp("created_at", {withTimezone:true, mode:"string"}).notNull().default(sql.raw("now()")),
 stripeCustomerId: text("stripe_customer_id"),
 notifyRescanComplete: boolean("notify_rescan_complete").notNull().default(sql.raw("true")),
 notifyRegressionAlert: boolean("notify_regression_alert").notNull().default(sql.raw("true")),
 notifyMonthlyDigest: boolean("notify_monthly_digest").notNull().default(sql.raw("true")),
 instagramHandle: text("instagram_handle"),
 slug: text("slug"),
 timezone: text("timezone").notNull().default(sql.raw("'Asia/Hong_Kong'::text")),
 isDemo: boolean("is_demo").notNull().default(sql.raw("false")),
}, t => [
 check("workspaces_market_check", sql.raw("(market = ANY (ARRAY['hk'::text, 'tw'::text]))")),
 primaryKey({name:"workspaces_pkey",columns:[t.id]}),
 check("workspaces_tier_check", sql.raw("(tier = ANY (ARRAY['lite'::text, 'paid'::text]))")),
 uniqueIndex("workspaces_slug_key").using("btree", sql.raw("slug")).where(sql.raw("(slug IS NOT NULL)")),
 pgPolicy("server_application", {for:"all", to:"sme_app_runtime", using:sql`true`, withCheck:sql`true`}),
]).enableRLS();
