import { writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { is, getTableName } from 'drizzle-orm';
import { PgTable } from 'drizzle-orm/pg-core';
import * as schema from '../lib/db/schema';
/** Generates typed row/insert mappings directly from the authored Neon schema, offline. */
export function generateTypes():string {
 const tables=Object.entries(schema).filter(([,value])=>is(value,PgTable)).sort(([a],[b])=>a.localeCompare(b));
 if(!tables.length)throw new Error('typed_schema_empty');
 const mapping=(kind:string)=>tables.map(([name,value])=>`  ${JSON.stringify(getTableName(value as PgTable))}: typeof schema.${name}.$infer${kind};`).join('\n');
 return `// Generated by corepack pnpm db:types. Do not edit.\nimport type * as schema from './schema';\nexport type DatabaseRows = {\n${mapping('Select')}\n};\nexport type DatabaseInserts = {\n${mapping('Insert')}\n};\n`;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){await writeFile(new URL('../lib/db/database.types.ts',import.meta.url),generateTypes(),'utf8');console.log('Generated Neon schema row and insert types.');}
