/**
 * Generate lib/supabase/database.types.ts from the migration corpus.
 *
 *   corepack pnpm db:types
 *
 * Migrations here are applied by hand through the Supabase dashboard, so the
 * corpus under supabase/migrations/ is the only machine-readable description
 * of the schema this repo has (CLAUDE.md 1.3.6). Rather than pointing the
 * Supabase CLI at the shared project (which would describe whatever is live,
 * including drift), this stands up a throwaway postgres:16 through the
 * integration harness, applies every migration in filename order, and runs
 * `supabase gen types typescript` against that container. The result is the
 * schema the corpus produces, which is the schema the app is written against.
 *
 * Requires Docker and the Supabase CLI (`supabase` on PATH, or resolvable via
 * `npx --no-install supabase`). Without Docker it refuses; without the CLI it
 * prints the exact command to run by hand and leaves the container up until
 * that command finishes, so the connection string it prints is live.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { dockerAvailable, startContainers } from "../test/integration/docker";
import { applySchema } from "../test/integration/schema";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = path.join(REPO_ROOT, "lib", "supabase", "database.types.ts");
// PostgREST refuses a JWT secret under 32 bytes; nothing here ever mints a token.
const JWT_SECRET = "sme-scanner-gen-types-jwt-secret-32b";
const IS_WINDOWS = process.platform === "win32";

type Cli = { command: string; args: string[] };

function tryCli(command: string, args: string[]): Cli | null {
  const probe = spawnSync(command, [...args, "--version"], { encoding: "utf8", shell: IS_WINDOWS, stdio: ["ignore", "pipe", "pipe"] });
  return probe.status === 0 ? { command, args } : null;
}

/** `supabase` on PATH first, then a project-local install via npx (never a download). */
function findSupabaseCli(): Cli | null {
  return tryCli("supabase", []) ?? tryCli("npx", ["--no-install", "supabase"]);
}

function generate(cli: Cli, dbUrl: string): string {
  const result = spawnSync(
    cli.command,
    [...cli.args, "gen", "types", "typescript", "--db-url", dbUrl, "--schema", "public"],
    { encoding: "utf8", shell: IS_WINDOWS, stdio: ["ignore", "pipe", "pipe"], maxBuffer: 64 * 1024 * 1024 },
  );
  if (result.status !== 0) {
    throw new Error(`supabase gen types failed (exit ${result.status}):\n${result.stderr}`);
  }
  return result.stdout;
}

async function main(): Promise<void> {
  if (!dockerAvailable()) {
    console.error(
      "db:types needs Docker to stand up a throwaway Postgres for the migration corpus.\n" +
        "Start Docker Desktop and re-run `corepack pnpm db:types`.",
    );
    process.exitCode = 1;
    return;
  }

  console.log("==> starting postgres:16 and applying supabase/migrations in filename order");
  const containers = await startContainers(JWT_SECRET);
  try {
    applySchema(process.pid.toString(36));

    const cli = findSupabaseCli();
    if (!cli) {
      console.error(
        [
          "The Supabase CLI is not installed, so the types were not generated.",
          "The migrated database is still running. In another terminal, run:",
          "",
          `  npx supabase gen types typescript --db-url "${containers.postgresUri}" --schema public > lib/supabase/database.types.ts`,
          "",
          "then press Enter here to stop the container. (Install the CLI with",
          "`corepack pnpm add -D supabase` or from https://supabase.com/docs/guides/cli.)",
        ].join("\n"),
      );
      await new Promise<void>((resolve) => {
        process.stdin.once("data", () => resolve());
        process.stdin.once("end", () => resolve());
        process.stdin.resume();
      });
      process.exitCode = 1;
      return;
    }

    console.log(`==> generating types with ${[cli.command, ...cli.args].join(" ")}`);
    const types = generate(cli, containers.postgresUri);
    const banner =
      "// Generated by scripts/gen-types.ts from supabase/migrations/*.sql applied to a local postgres:16.\n" +
      "// Do not edit by hand; re-run `corepack pnpm db:types` after adding a migration.\n\n";
    mkdirSync(path.dirname(OUTPUT), { recursive: true });
    writeFileSync(OUTPUT, banner + types, "utf8");
    console.log(`==> wrote ${path.relative(REPO_ROOT, OUTPUT)}`);
  } finally {
    containers.stop();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
