import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { beforeAll, afterAll, beforeEach, afterEach, describe, it, expect, vi } from 'vitest';
import { applyMigrations } from '../../scripts/neon/migrations';
import { startNeonDatabaseFixture, type NeonDatabaseFixture } from './neon-database';
import { rescanRepository } from '../../lib/repositories/rescan';
import { workspaceProfileRepository } from '../../lib/repositories/workspace-profile';
import { enqueueRescan, ensureMonthlySchedule } from '../../lib/workspace/rescan';
const ports=vi.hoisted(()=>({pool:undefined as Pool|undefined}));
vi.mock('../../lib/db/client',()=>({getPool:()=>ports.pool,getDatabase:()=>drizzle(ports.pool!)}));
vi.mock('../../lib/supabase/admin',()=>({supabaseServer:()=>{throw new Error('legacy transport forbidden');}}));
const snapshot={version:2,market:'TW',locale:'zh-TW',businessName:'台北 fixture',industry:'fnb',district:'taipei',objective:'more_leads',placeId:'fixture-place',instagramHandle:'fixture',instagramMatchProvenance:'manual_typed'};
describe.runIf(process.env.NEON_INTEGRATION==='1')('Neon rescan and owner profile persistence',()=>{
 let fixture:NeonDatabaseFixture,owner:Pool,runtime:Pool;
 beforeAll(async()=>{fixture=await startNeonDatabaseFixture('test');owner=new Pool({connectionString:fixture.databaseUrl});await owner.query("CREATE ROLE sme_app_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; CREATE ROLE fixture_runtime LOGIN PASSWORD 'fixture-only' IN ROLE sme_app_runtime");await applyMigrations(owner);const url=new URL(fixture.databaseUrl);url.username='fixture_runtime';url.password='fixture-only';runtime=new Pool({connectionString:url.href});ports.pool=runtime;});
 beforeEach(async()=>{vi.stubGlobal('fetch',()=>{throw new Error('transport forbidden');});await runtime.query('DELETE FROM scan_schedules; DELETE FROM audit_jobs; DELETE FROM workspaces; DELETE FROM app_users');});
 afterEach(()=>vi.unstubAllGlobals());
 afterAll(async()=>{await Promise.all([owner?.end(),runtime?.end()]);fixture?.stop();});
 async function setup(){const ws=(await runtime.query("INSERT INTO workspaces(slug,market,tier) VALUES('rescan','tw','paid') RETURNING id")).rows[0].id;const loc=(await runtime.query("INSERT INTO locations(workspace_id,slug,name,is_primary) VALUES($1,'main','Main',true) RETURNING id",[ws])).rows[0].id;const actor=(await runtime.query("INSERT INTO app_users(email) VALUES('actor@example.test') RETURNING id")).rows[0].id;const job=(await runtime.query("INSERT INTO audit_jobs(business_name,workspace_id,location_id,status,created_at,input_snapshot,place_id) VALUES('Fixture',$1,$2,'done','2026-08-15',$3,'fixture-place') RETURNING id",[ws,loc,JSON.stringify(snapshot)])).rows[0].id;return {ws,loc,actor,job};}
 it('reads only the newest finished owned location job and distinguishes missing/error',async()=>{const {ws,loc,job}=await setup(),repo=rescanRepository(runtime);await runtime.query("INSERT INTO audit_jobs(business_name,workspace_id,location_id,status) VALUES('New queued',$1,$2,'queued')",[ws,loc]);expect(await repo.latestFinishedJob(ws,loc)).toMatchObject({id:job,input_snapshot:{locale:'zh-TW',market:'TW'}});expect(await repo.latestFinishedJob(crypto.randomUUID(),loc)).toBeNull();expect(await repo.tier(ws)).toBe('paid');expect(await repo.tier(crypto.randomUUID())).toBeNull();const closed=new Pool({connectionString:fixture.databaseUrl});await closed.end();await expect(rescanRepository(closed).latestFinishedJob(ws,loc)).rejects.toThrow();await expect(rescanRepository(closed).tier(ws)).rejects.toThrow();});
 it('enqueues actual TW jobs and server-attributed audit, then monthly schedule once',async()=>{const {ws,loc,actor,job}=await setup(),repo=rescanRepository(runtime);const result=await enqueueRescan(repo,{workspaceId:ws,locationId:loc,actorId:actor,locale:'zh-TW'});expect(result.ok).toBe(true);if(!result.ok)throw new Error('enqueue failed');expect((await runtime.query('SELECT workspace_id,location_id,parent_job_id,status,region,input_snapshot FROM audit_jobs WHERE id=$1',[result.jobId])).rows[0]).toMatchObject({workspace_id:ws,location_id:loc,parent_job_id:job,status:'queued',region:'tw',input_snapshot:{locale:'zh-TW',market:'TW'}});expect((await runtime.query('SELECT actor_id,payload FROM audit_events WHERE entity_id=$1',[result.jobId])).rows[0]).toMatchObject({actor_id:actor,payload:{locale:'zh-TW',trigger:'rescan',parent_job_id:job}});const input={job:result.sourceJob,workspaceId:ws,actorId:actor,nowIso:'2026-09-06T00:00:00Z'};expect(await ensureMonthlySchedule(repo,input)).toEqual({created:true});expect(await ensureMonthlySchedule(repo,input)).toEqual({created:false,reason:'exists'});expect((await runtime.query('SELECT cadence,anniversary_day,workspace_id,created_by,last_job_id FROM scan_schedules')).rows).toEqual([{cadence:'monthly',anniversary_day:15,workspace_id:ws,created_by:actor,last_job_id:job}]);});
 it('preserves a concurrent unique schedule winner and reports SQL lookup failures',async()=>{const {ws,loc,actor}=await setup(),repo=rescanRepository(runtime),source=(await repo.latestFinishedJob(ws,loc))!;const input={job:source,workspaceId:ws,actorId:actor,nowIso:'2026-09-06T00:00:00Z'};expect(await ensureMonthlySchedule(repo,input)).toEqual({created:true});expect(await ensureMonthlySchedule({...repo,scheduleExists:async()=>false},input)).toEqual({created:false,reason:'exists'});const closed=new Pool({connectionString:fixture.databaseUrl});await closed.end();expect(await ensureMonthlySchedule(rescanRepository(closed),input)).toEqual({created:false,reason:'lookup_failed'});});
 it('updates only the authorized workspace and its primary location',async()=>{const {ws,loc}=await setup();const other=(await runtime.query("INSERT INTO workspaces(slug) VALUES('foreign') RETURNING id")).rows[0].id;const secondary=(await runtime.query("INSERT INTO locations(workspace_id,slug,name) VALUES($1,'secondary','Secondary') RETURNING id",[ws])).rows[0].id;const foreign=(await runtime.query("INSERT INTO locations(workspace_id,slug,name,is_primary) VALUES($1,'foreign','Foreign',true) RETURNING id",[other])).rows[0].id;const repo=workspaceProfileRepository(runtime);await repo.setInstagramHandle(ws,'taipei');await repo.syncPrimaryInstagramHandle(ws,'taipei');expect((await runtime.query('SELECT instagram_handle FROM workspaces WHERE id=$1',[ws])).rows[0].instagram_handle).toBe('taipei');expect((await runtime.query('SELECT ig_handle FROM locations WHERE id=$1',[loc])).rows[0].ig_handle).toBe('taipei');expect((await runtime.query('SELECT ig_handle FROM locations WHERE id=ANY($1::uuid[])',[[secondary,foreign]])).rows).toEqual([{ig_handle:null},{ig_handle:null}]);expect((await runtime.query('SELECT instagram_handle FROM workspaces WHERE id=$1',[other])).rows[0].instagram_handle).toBeNull();});
});
